/**
 * The skin preset library — moods every room can wear. Each room also has
 * its own signature preset (rooms.ts). Names are English inside tr();
 * German in lib/i18n/de/skins.ts. `ref` points at the mood board
 * (docs/SKINS.md § References, pictures 1 … 9).
 */
import { tr } from "@/lib/i18n";
import type { SkinPreset } from "@/lib/world/skins/types";

const P = (p: SkinPreset): SkinPreset => p;

export const SKIN_PRESETS: readonly SkinPreset[] = [
  P({
    id: "work",
    name: tr("Work light"),
    line: "#e8e4d8",
    node: "#ffffff",
    field: "#5b6068",
    fieldGlow: 0,
    mode: "static",
    speed: 1,
    intensity: 0.35,
  }),
  P({
    id: "amber_outline",
    name: tr("Amber outline"),
    line: "#ffb800",
    node: "#ffcf40",
    field: "#0a0806",
    fieldGlow: 0,
    mode: "static",
    speed: 1,
    intensity: 1,
    ref: [2],
  }),
  P({
    id: "sodium",
    name: tr("Sodium"),
    line: "#3a1606",
    node: "#ffc040",
    field: "#e0661a",
    fieldGlow: 0.9,
    mode: "static",
    speed: 1,
    intensity: 0.9,
    ref: [3],
  }),
  P({
    id: "lemon",
    name: tr("Lemon"),
    line: "#3a3204",
    node: "#f4ff6a",
    field: "#d9c41e",
    fieldGlow: 0.9,
    mode: "static",
    speed: 1,
    intensity: 0.9,
    ref: [4],
  }),
  P({
    id: "red_room",
    name: tr("Red room"),
    line: "#2a0202",
    node: "#ff5a3a",
    field: "#c40d0d",
    fieldGlow: 0.85,
    mode: "breathe",
    speed: 0.4,
    intensity: 0.85,
    ref: [5],
  }),
  P({
    id: "ink_red",
    name: tr("Red ink"),
    line: "#000000",
    node: "#ff2a1a",
    field: "#c00000",
    fieldGlow: 0.35,
    mode: "static",
    speed: 1,
    intensity: 1,
    ref: [1],
  }),
  P({
    id: "ink_teal",
    name: tr("Teal ink"),
    line: "#000000",
    node: "#5cf2ff",
    field: "#0fc4b0",
    fieldGlow: 0.35,
    mode: "static",
    speed: 1,
    intensity: 1,
    ref: [6],
  }),
  P({
    id: "tunnel",
    name: tr("Tunnel"),
    line: "#f0f02a",
    node: "#ffffff",
    field: "#2a2a04",
    fieldGlow: 0.2,
    mode: "chase",
    speed: 0.6,
    intensity: 1,
    ref: [7],
  }),
  P({
    id: "cathedral",
    name: tr("Cathedral"),
    line: "#ff9a00",
    node: "#ff5a00",
    field: "#1a0800",
    fieldGlow: 0.1,
    mode: "flicker",
    speed: 0.3,
    intensity: 1,
    ref: [8],
  }),
  P({
    id: "grid_blue",
    name: tr("Grid blue"),
    line: "#4ab8ff",
    node: "#bfe8ff",
    field: "#050a3a",
    fieldGlow: 0.25,
    mode: "scan",
    speed: 0.5,
    intensity: 1,
    ref: [9],
  }),
  P({
    id: "phosphor",
    name: tr("Phosphor"),
    line: "#33ff33",
    node: "#b8ffb8",
    field: "#020a02",
    fieldGlow: 0.1,
    mode: "rain",
    speed: 1,
    intensity: 0.9,
  }),
  P({
    id: "night",
    name: tr("Night watch"),
    line: "#2f5bff",
    node: "#6a8cff",
    field: "#14161c",
    fieldGlow: 0,
    mode: "breathe",
    speed: 0.25,
    intensity: 0.3,
  }),
  P({
    id: "aurora",
    name: tr("Aurora"),
    line: "#00ffaa",
    line2: "#8b00ff",
    node: "#c8fff0",
    field: "#060c12",
    fieldGlow: 0.15,
    mode: "cycle",
    speed: 1,
    intensity: 0.85,
  }),
  P({
    id: "heat",
    name: tr("Heat map"),
    line: "#ff4a1a",
    node: "#ffd040",
    field: "#200804",
    fieldGlow: 0.2,
    mode: "reactive",
    speed: 1,
    intensity: 1,
    source: "heat",
  }),
  P({
    id: "load",
    name: tr("Load meter"),
    line: "#00ff66",
    node: "#ffb800",
    field: "#0a120c",
    fieldGlow: 0.1,
    mode: "reactive",
    speed: 1,
    intensity: 1,
    source: "load",
  }),
  P({
    id: "spectrum",
    name: tr("Spectrum"),
    line: "#ff00ff",
    line2: "#00ffff",
    node: "#ffffff",
    field: "#0c0612",
    fieldGlow: 0.1,
    mode: "meter",
    speed: 1,
    intensity: 1,
    source: "signal",
  }),
  P({
    id: "dawn",
    name: tr("Dawn"),
    line: "#ffd9a0",
    node: "#ffb070",
    field: "#8a816c",
    fieldGlow: 0.15,
    mode: "daylight",
    speed: 1,
    intensity: 0.8,
    source: "clock",
  }),
  P({
    id: "cryo",
    name: tr("Cryo"),
    line: "#00ffff",
    node: "#e0ffff",
    field: "#bfefff",
    fieldGlow: 0.35,
    mode: "breathe",
    speed: 0.2,
    intensity: 0.8,
  }),
  P({
    id: "abyss",
    name: tr("Abyss"),
    line: "#20083a",
    node: "#9d5cff",
    field: "#060408",
    fieldGlow: 0,
    mode: "heartbeat",
    speed: 0.6,
    intensity: 1,
  }),
  P({
    id: "gold",
    name: tr("Gold leaf"),
    line: "#e0b64a",
    node: "#fff0a0",
    field: "#120c00",
    fieldGlow: 0.05,
    mode: "twinkle",
    speed: 0.6,
    intensity: 1,
  }),
  P({
    id: "starlight",
    name: tr("Starlight"),
    line: "#3a4a8a",
    node: "#ffffff",
    field: "#02030a",
    fieldGlow: 0,
    mode: "twinkle",
    speed: 0.5,
    intensity: 1,
  }),
  P({
    id: "alarm",
    name: tr("Alarm"),
    line: "#ff2020",
    node: "#ff2020",
    field: "#300000",
    fieldGlow: 0.3,
    mode: "alarm",
    speed: 1,
    intensity: 1,
  }),
  P({
    id: "emergency",
    name: tr("Emergency light"),
    line: "#000000",
    node: "#ff3020",
    field: "#16100f",
    fieldGlow: 0,
    mode: "breathe",
    speed: 0.3,
    intensity: 0.5,
  }),
  P({
    id: "off",
    name: tr("Off"),
    line: "#000000",
    node: "#000000",
    field: "#5b6068",
    fieldGlow: 0,
    mode: "off",
    speed: 1,
    intensity: 0,
  }),
];

const BY_ID = new Map(SKIN_PRESETS.map((p) => [p.id, p]));

export function skinPreset(id: string): SkinPreset | undefined {
  return BY_ID.get(id);
}

/** Presets the lab forces for a while (events), never chosen as a room default. */
export const FORCED_PRESETS: readonly string[] = ["alarm", "emergency"];
