/**
 * One skin concept per room (docs/SKINS.md § Rooms). Every concept is
 * complete enough to build: wall family + parameters, bands and glyphs,
 * floor family, a signature mood, recommended presets and the events that
 * take the skin over. `voxels.ts` turns it into fine voxels; the Blender
 * renders (pnpm skins:render) are made from exactly this data.
 *
 * Wall face coordinates (fine voxels, 4 per source voxel): v 0 … 3 base,
 * v 4 … 27 panel zone (24 high), v 28 … 31 cap. Bands use v in the panel zone.
 */
import { tr } from "@/lib/i18n";
import type {
  FloorSpec,
  RoomSkin,
  SkinMode,
  SkinPreset,
  SkinSource,
  WallSpec,
} from "@/lib/world/skins/types";

type WallIn = Partial<Omit<WallSpec, "paint">> & { paint?: Partial<WallSpec["paint"]> };
type FloorIn = Partial<Omit<FloorSpec, "paint">> & { paint?: Partial<FloorSpec["paint"]> };

const WALL0: WallSpec = {
  family: "grid",
  panel: 8,
  rows: 4,
  seam: 1,
  relief: "inset",
  base: "plain",
  paint: {
    panel: "field",
    seam: "line",
    base: "metal_dark",
    cap: "wall_trim",
    inlay: "black",
    dark: "black",
    accent: "line",
    dado: "oak",
  },
  dado: "raised",
  dark: 0,
  inlays: 0,
  glyphs: "tetro",
  nodes: false,
  bezel: false,
  bands: [],
  cornice: "none",
  pillar: 0,
  cracks: false,
  crackGlow: "line",
};

const FLOOR0: FloorSpec = {
  family: "tiles",
  tile: 16,
  paint: {
    a: "floor_tile",
    b: "floor_dark",
    grout: "floor_dark",
    border: "metal_dark",
    line: "line",
    node: "node",
  },
  lines: "none",
  diamonds: false,
  cracks: false,
};

function wall(family: WallSpec["family"], o: WallIn = {}): WallSpec {
  return { ...WALL0, ...o, family, paint: { ...WALL0.paint, ...o.paint } };
}

function floor(family: FloorSpec["family"], o: FloorIn = {}): FloorSpec {
  return { ...FLOOR0, ...o, family, paint: { ...FLOOR0.paint, ...o.paint } };
}

function sig(
  room: string,
  name: string,
  line: string,
  node: string,
  field: string,
  fieldGlow: number,
  mode: SkinMode,
  speed = 1,
  intensity = 1,
  source?: SkinSource,
  line2?: string,
): SkinPreset {
  return {
    id: `sig_${room}`,
    name,
    line,
    line2,
    node,
    field,
    fieldGlow,
    mode,
    speed,
    intensity,
    source,
  };
}

/** Lore: the data center LED blinks 847 ms on, 847 ms off (pulse period = 2 s / speed). */
const SPEED_847 = 1 / 0.847;

export const ROOM_SKINS: readonly RoomSkin[] = [
  // ── Ebene 0 ──────────────────────────────────────────────────────
  {
    room: "kontroll",
    title: tr("Command wall"),
    idea: tr(
      "The wall behind the Main Console is the mood board come true: four rows of square panels with deep seams, dark tetromino inlays and a bevelled cornice like a ceiling edge. One geometry wears every mood — amber outlines, sodium light boxes, lemon, red room or grid blue.",
    ),
    wall: wall("grid", {
      panel: 8,
      rows: 4,
      dark: 5,
      inlays: 0.22,
      nodes: true,
      cornice: "chamfer",
      paint: { cap: "metal_dark" },
    }),
    floor: floor("tiles", {
      tile: 16,
      diamonds: true,
      paint: { a: "floor_tile", b: "floor_dark", grout: "black" },
    }),
    signature: sig("kontroll", tr("Console amber"), "#ffb800", "#ffcf40", "#0a0806", 0, "static"),
    alts: ["sodium", "lemon", "red_room", "grid_blue", "amber_outline"],
    events: [
      tr("Console session starts: a scan sweeps once from floor to cornice."),
      tr("MCP alert: the field flushes red (Red room) until it is acknowledged."),
    ],
    ref: [2, 3, 4, 5],
  },
  {
    room: "mcp",
    title: tr("The red eye's iris"),
    idea: tr(
      "Rack fronts all around, cold and dark, with one red line pulsing through every seam in the MCP's heartbeat. The raised floor glows red through its perforations. The whole room is the eye that blinks very slowly.",
    ),
    wall: wall("rack", {
      panel: 8,
      paint: { panel: "metal_dark", seam: "line", cap: "metal_dark", accent: "node" },
      cornice: "cove",
    }),
    floor: floor("raised", {
      tile: 8,
      lines: "none",
      paint: { a: "floor_red", b: "metal_dark", grout: "black" },
    }),
    signature: sig(
      "mcp",
      tr("Red eye"),
      "#ff2a1a",
      "#ff6a40",
      "#140404",
      0.1,
      "heartbeat",
      0.6,
      1,
      "load",
    ),
    alts: ["abyss", "ink_red", "load", "night"],
    events: [tr("Kernel load above 80 %: the heartbeat doubles its tempo.")],
    ref: [1, 5],
  },
  {
    room: "sekundaer",
    title: tr("Night-shift office"),
    idea: tr(
      "Damien's monitoring station from the late eighties: oak wainscot, a cream upper wall with a thin damask dot, a row of small monitor bezels along the chair rail. A warm cove light under the cornice is the only lamp that is always on.",
    ),
    wall: wall("wainscot", {
      panel: 12,
      paint: { panel: "field", seam: "wood_dark", cap: "walnut", accent: "node" },
      bands: [{ v0: 13, v1: 15, kind: "light" }],
      cornice: "cove",
    }),
    floor: floor("terrazzo", {
      paint: { a: "floor_beige", b: "beige_dk", grout: "floor_beige_dk" },
    }),
    signature: sig(
      "sekundaer",
      tr("Desk lamp"),
      "#ffd9a0",
      "#33ff33",
      "#8a816c",
      0.12,
      "breathe",
      0.15,
      0.8,
    ),
    alts: ["dawn", "night", "ink_teal", "work"],
    events: [tr("Synapsis headset in use: the monitor row turns green.")],
    ref: [6],
  },
  {
    room: "westflur",
    title: tr("Counting corridor"),
    idea: tr(
      "A tunnel of ribs every six voxels, each rib a day mark. Horizontal panel bands run between the ribs, a light line rides along them toward the control room, and diamond markers on the floor count the steps. Ref 7 in a straight corridor.",
    ),
    wall: wall("rib", {
      panel: 24,
      rows: 3,
      pillar: 6,
      cornice: "chamfer",
      paint: { panel: "field", seam: "metal_dark", accent: "line", cap: "metal_dark" },
    }),
    floor: floor("guide", { tile: 16, lines: "center", diamonds: true }),
    signature: sig(
      "westflur",
      tr("Day counter"),
      "#f0f02a",
      "#ffffff",
      "#3a3c30",
      0.15,
      "chase",
      0.6,
    ),
    alts: ["tunnel", "grid_blue", "night", "work"],
    events: [tr("Jade walks the corridor: the chase follows her pace.")],
    ref: [7],
  },
  {
    room: "werkstatt",
    title: tr("Shadow board"),
    idea: tr(
      "Pegboard panels with painted tool silhouettes — every tool has its place, the empty outlines show what is out on a bench. Hazard-striped baseboard, task light strips in the cove, an epoxy floor with yellow lanes and oil spots.",
    ),
    wall: wall("pegboard", {
      panel: 16,
      rows: 2,
      base: "hazard",
      inlays: 0.75,
      glyphs: "tools",
      cornice: "cove",
      paint: { panel: "field", seam: "olive_dk", inlay: "safety_red", cap: "olive_dk" },
    }),
    floor: floor("epoxy", { paint: { a: "floor_green", b: "olive_dk", border: "safety_yellow" } }),
    signature: sig(
      "werkstatt",
      tr("Workbench"),
      "#fff2d8",
      "#ff7a00",
      "#4a5040",
      0,
      "static",
      1,
      0.8,
    ),
    alts: ["sodium", "work", "amber_outline", "alarm"],
    events: [tr("A device is being built: the node lights run like a progress bar.")],
    ref: [3],
  },
  {
    room: "archiv",
    title: tr("Card index"),
    idea: tr(
      "The walls are drawers: rows of small index-card fronts with brass pulls and tiny label lights. When the Crystal Data Cache is powered the labels twinkle as if someone were looking things up.",
    ),
    wall: wall("drawers", {
      panel: 6,
      rows: 6,
      paint: { panel: "field", seam: "teal_dk", accent: "brass", cap: "teal_dk" },
    }),
    floor: floor("tiles", {
      tile: 12,
      paint: { a: "floor_blue", b: "paint_navy", grout: "black" },
    }),
    signature: sig(
      "archiv",
      tr("Index light"),
      "#3fd0ff",
      "#ffb800",
      "#2d6b6b",
      0.12,
      "twinkle",
      0.4,
      0.9,
      "power",
    ),
    alts: ["ink_teal", "cryo", "night", "work"],
    events: [tr("CDC-001 indexing: label lights chase along the rows.")],
    ref: [6],
  },
  {
    room: "aufzug0",
    title: tr("Compass rotunda"),
    idea: tr(
      "The command rotunda is a compass. Outlined panels run around the core, pillars mark the eight winds, and the floor carries rings and spokes with an amber needle toward the control room. Light ripples outward from the shaft whenever the elevator arrives.",
    ),
    wall: wall("grid", {
      panel: 8,
      rows: 3,
      bezel: true,
      pillar: 8,
      cornice: "chamfer",
      paint: { panel: "field", seam: "black", accent: "line", cap: "metal_dark" },
    }),
    floor: floor("rings", { tile: 12, paint: { a: "floor_tile", b: "floor_dark" } }),
    signature: sig("aufzug0", tr("Compass"), "#ffb800", "#ffffff", "#16181c", 0, "ripple", 0.5),
    alts: ["grid_blue", "amber_outline", "tunnel", "night"],
    events: [tr("Elevator arrives: one ripple from the shaft to the walls.")],
    ref: [2, 9],
  },
  {
    room: "schleuse",
    title: tr("Pressure cycle"),
    idea: tr(
      "Riveted olive plates, hazard-striped baseboard, a red warning band at shoulder height and status nodes beside the doors. While the airlock cycles the band pulses, then a light runs toward the door that may open.",
    ),
    wall: wall("plate", {
      panel: 16,
      rows: 2,
      base: "hazard",
      bands: [{ v0: 15, v1: 16, kind: "light" }],
      paint: { panel: "wall_olive", seam: "olive_dk", accent: "chrome", cap: "olive_dk" },
    }),
    floor: floor("grate", { paint: { a: "floor_grate", b: "black", border: "safety_yellow" } }),
    signature: sig(
      "schleuse",
      tr("Lock cycle"),
      "#ff3020",
      "#ffb800",
      "#4a5040",
      0,
      "pulse",
      1,
      0.9,
    ),
    alts: ["alarm", "amber_outline", "work", "night"],
    events: [tr("Door cycle: pulse, then a chase toward the released door.")],
    ref: [5],
  },
  {
    room: "kartenraum",
    title: tr("Red threads"),
    idea: tr(
      "Old brick behind a cork band, pinned with notes; red threads run between the pins across the whole room — they are the line channel. In the dark only the threads glow, as if the map were thinking.",
    ),
    wall: wall("brick", {
      rows: 8,
      panel: 8,
      bands: [
        { v0: 10, v1: 21, kind: "threads" },
        { v0: 22, v1: 23, kind: "light" },
      ],
      paint: { panel: "brick", seam: "mortar", cap: "walnut", accent: "paper_yellow" },
    }),
    floor: floor("planks", { tile: 4, paint: { a: "wood", b: "wood_dark", grout: "walnut" } }),
    signature: sig(
      "kartenraum",
      tr("Thread map"),
      "#ff2a1a",
      "#ffd9a0",
      "#7e3a2c",
      0,
      "breathe",
      0.2,
    ),
    alts: ["ink_red", "emergency", "dawn"],
    events: [tr("A map clue solved: its thread flashes three times.")],
    ref: [1],
  },
  {
    room: "kabelgang",
    title: tr("Warm cables"),
    idea: tr(
      "Thigh-thick cable bundles fill the panel zone, held by steel clamps every two voxels. A light pulse travels along the bundles from the control room to the MCP — the data you just typed, on its way.",
    ),
    wall: wall("grid", {
      panel: 8,
      rows: 1,
      bands: [{ v0: 5, v1: 25, kind: "cables" }],
      paint: { panel: "metal_dark", seam: "steel_dark", cap: "metal_dark" },
    }),
    floor: floor("grate", { paint: { a: "floor_grate", b: "black", border: "metal_dark" } }),
    signature: sig(
      "kabelgang",
      tr("Data in transit"),
      "#ff7a1a",
      "#ffb800",
      "#1f2226",
      0,
      "chase",
      1.2,
    ),
    alts: ["phosphor", "tunnel", "night"],
    events: [tr("A terminal command runs: one pulse per command.")],
    ref: [7],
  },
  {
    room: "archivgang",
    title: tr("Stubborn passage"),
    idea: tr(
      "A narrow tiled passage with one fluorescent band that never quite settles. Guide lines on the floor lead to the archive door that has been electric since 1998 and stubborn since 2019.",
    ),
    wall: wall("tile", {
      panel: 4,
      rows: 6,
      bands: [{ v0: 20, v1: 21, kind: "light" }],
      paint: { panel: "field", seam: "steel_dark", cap: "metal_dark" },
    }),
    floor: floor("guide", { tile: 8, lines: "sides" }),
    signature: sig(
      "archivgang",
      tr("Tired tube"),
      "#e8f4ff",
      "#ffb800",
      "#5b6068",
      0.05,
      "flicker",
      0.6,
      0.8,
    ),
    alts: ["work", "night", "ink_teal"],
    events: [tr("Archive door jams: the band dies for a second.")],
    ref: [],
  },

  // ── Ebene −1 ─────────────────────────────────────────────────────
  {
    room: "aufzug1",
    title: tr("Busbar ring"),
    idea: tr(
      "Copper busbars, thick as an arm, circle the distribution core in three horizontal bands with steel clamps. The current is visible: a chase runs along the bars, its speed and brightness follow the lab's real power flow.",
    ),
    wall: wall("grid", {
      panel: 16,
      rows: 1,
      pillar: 8,
      bands: [{ v0: 8, v1: 23, kind: "busbar" }],
      paint: { panel: "metal_dark", seam: "steel_dark", cap: "copper" },
    }),
    floor: floor("rings", { paint: { a: "floor_grate", b: "metal_dark", grout: "black" } }),
    signature: sig(
      "aufzug1",
      tr("skin::Current"),
      "#ff7a1a",
      "#ffd040",
      "#1f2226",
      0,
      "chase",
      0.8,
      1,
      "power",
    ),
    alts: ["heat", "amber_outline", "tunnel"],
    events: [tr("Brownout: the chase stops, the bars dim to ember.")],
    ref: [8],
  },
  {
    room: "versorgung",
    title: tr("Hum"),
    idea: tr(
      "A utility corridor of plain plates and ribs; cable trays above. The light is an old fluorescent strip that hums and flickers, and the guide line on the floor glows a little brighter wherever a cable is warm.",
    ),
    wall: wall("rib", {
      panel: 16,
      rows: 2,
      pillar: 8,
      paint: { panel: "field", seam: "wall_dk", accent: "line", cap: "metal_dark" },
    }),
    floor: floor("guide", { tile: 16, lines: "center" }),
    signature: sig(
      "versorgung",
      tr("Fluorescent"),
      "#e8f4ff",
      "#ffb800",
      "#5b6068",
      0.05,
      "flicker",
      0.4,
      0.7,
    ),
    alts: ["tunnel", "work", "night"],
    events: [],
    ref: [7],
  },
  {
    room: "geo",
    title: tr("Thermal vein"),
    idea: tr(
      "Raw formwork concrete with tie holes, a copper pipe band and cracks that glow from inside. The light is the rock's heat: it breathes slowly and turns brighter the hotter the borehole runs.",
    ),
    wall: wall("plate", {
      panel: 32,
      rows: 2,
      relief: "flat",
      cracks: true,
      bands: [{ v0: 21, v1: 23, kind: "pipes" }],
      paint: {
        panel: "concrete",
        seam: "concrete_dark",
        accent: "concrete_dark",
        cap: "concrete_dark",
      },
    }),
    floor: floor("concrete", {
      tile: 32,
      cracks: true,
      paint: { a: "concrete_dark", b: "concrete", grout: "asphalt" },
    }),
    signature: sig(
      "geo",
      tr("Magma"),
      "#ff6b00",
      "#ff4a1a",
      "#55554f",
      0,
      "breathe",
      0.2,
      1,
      "heat",
    ),
    alts: ["heat", "cathedral", "emergency"],
    events: [tr("Seep valve opens: the cracks flare violet for a moment.")],
    ref: [8],
  },
  {
    room: "batterie",
    title: tr("Charge rack"),
    idea: tr(
      "Battery cell racks line the walls; each cell front carries a charge bar of node lights. The bars show the lab's real charge — green when full, sinking and turning amber as it drains. Rubber floor mats with hazard edges.",
    ),
    wall: wall("rack", {
      panel: 12,
      base: "hazard",
      paint: { panel: "metal_dark", seam: "steel_dark", accent: "node", cap: "metal_dark" },
    }),
    floor: floor("tiles", {
      tile: 16,
      paint: { a: "rubber", b: "floor_tile", grout: "black", border: "safety_yellow" },
    }),
    signature: sig(
      "batterie",
      tr("skin::Charge"),
      "#00ff66",
      "#00ff66",
      "#1f2226",
      0,
      "meter",
      1,
      1,
      "charge",
    ),
    alts: ["load", "amber_outline", "emergency"],
    events: [tr("Charge below 15 %: the bars blink amber.")],
    ref: [],
  },
  {
    room: "kuehlung",
    title: tr("Frost tile"),
    idea: tr(
      "White and teal tiles with a frosted band at head height, drains in the floor. The cold is a colour: the light breathes ice-cyan and goes deeper blue the colder the coolant runs.",
    ),
    wall: wall("tile", {
      panel: 4,
      rows: 6,
      bands: [{ v0: 22, v1: 25, kind: "frost" }],
      paint: { panel: "field", seam: "steel_dark", cap: "aluminium" },
    }),
    floor: floor("tiles", {
      tile: 8,
      paint: { a: "tile_white", b: "tile_teal", grout: "steel_dark" },
    }),
    signature: sig(
      "kuehlung",
      tr("Coolant"),
      "#00ffff",
      "#e0ffff",
      "#c9ccd0",
      0.2,
      "breathe",
      0.2,
      0.85,
      "heat",
    ),
    alts: ["cryo", "ink_teal", "work"],
    events: [tr("Overheat: the band turns orange until the coolant catches up.")],
    ref: [6],
  },
  {
    room: "kuehlgang",
    title: tr("Condensate"),
    idea: tr(
      "Frosted aluminium pipes run the length of the passage; condensate drips from them as falling light. The floor grate is wet and reflects it.",
    ),
    wall: wall("grid", {
      panel: 8,
      rows: 1,
      bands: [
        { v0: 6, v1: 11, kind: "pipes" },
        { v0: 16, v1: 21, kind: "pipes" },
      ],
      paint: { panel: "field", seam: "steel_dark", cap: "aluminium" },
    }),
    floor: floor("grate", { paint: { a: "floor_grate", b: "puddle" } }),
    signature: sig(
      "kuehlgang",
      tr("Drip"),
      "#3fd0ff",
      "#e0ffff",
      "#aeb4ba",
      0.05,
      "rain",
      0.4,
      0.9,
    ),
    alts: ["cryo", "night"],
    events: [],
    ref: [],
  },
  {
    room: "fertigung",
    title: tr("Assembly line"),
    idea: tr(
      "Big riveted plates with hazard chevrons, gantry rails as pillars, an epoxy floor with yellow lanes and glowing bot bays. A yellow chase runs around the hall in time with production; when a fabricator finishes, the bay lines flash.",
    ),
    wall: wall("plate", {
      panel: 24,
      rows: 2,
      base: "hazard",
      pillar: 12,
      inlays: 0.3,
      glyphs: "chevrons",
      paint: {
        panel: "field",
        seam: "olive_dk",
        accent: "chrome",
        cap: "olive_dk",
        inlay: "safety_yellow",
      },
    }),
    floor: floor("epoxy", {
      lines: "sides",
      paint: { a: "floor_grate", b: "olive_dk", border: "safety_yellow" },
    }),
    signature: sig(
      "fertigung",
      tr("Production"),
      "#ffd400",
      "#ffffff",
      "#4a5040",
      0,
      "chase",
      0.8,
      1,
      "load",
    ),
    alts: ["sodium", "lemon", "alarm", "work"],
    events: [tr("Craft finished: bay lines flash twice.")],
    ref: [4],
  },
  {
    room: "rechen",
    title: tr("847 ms"),
    idea: tr(
      "Server rack fronts with vent slits and status LEDs, a cold-aisle line in blue along the seams, and a raised perforated floor that glows from below. One LED pattern runs through the whole room: 847 ms on, 847 ms off.",
    ),
    wall: wall("rack", {
      panel: 8,
      cornice: "cove",
      paint: { panel: "metal_dark", seam: "line", accent: "node", cap: "metal_dark" },
    }),
    floor: floor("raised", {
      tile: 8,
      paint: { a: "floor_blue", b: "metal_dark", grout: "black" },
    }),
    signature: sig(
      "rechen",
      tr("847 ms"),
      "#2f7bff",
      "#00ff66",
      "#1f2226",
      0,
      "pulse",
      SPEED_847,
      1,
      "load",
    ),
    alts: ["grid_blue", "phosphor", "load", "night"],
    events: [tr("CPU at full load: the LEDs switch to rain.")],
    ref: [9],
  },
  {
    room: "lager",
    title: tr("Stock bays"),
    idea: tr(
      "Shelf bays painted beige with stencilled bay numbers, a blue safety band, and floor markings for pallets. In smoke the blue light draws visible beams; once the ventilation runs, the numbers glow clear.",
    ),
    wall: wall("grid", {
      panel: 16,
      rows: 2,
      inlays: 0.6,
      glyphs: "digits",
      bands: [{ v0: 15, v1: 16, kind: "light" }],
      paint: { panel: "field", seam: "wall_beige_dk", inlay: "safety_blue", cap: "wall_beige_dk" },
    }),
    floor: floor("concrete", {
      tile: 24,
      lines: "both",
      paint: {
        a: "floor_beige",
        b: "floor_beige_dk",
        grout: "floor_beige_dk",
        border: "safety_yellow",
      },
    }),
    signature: sig("lager", tr("Stock"), "#1f8fff", "#ffffff", "#8a816c", 0, "static", 1, 0.8),
    alts: ["work", "lemon", "night"],
    events: [tr("Pickup in the store: its bay number flashes.")],
    ref: [],
  },

  // ── Ebene −2 ─────────────────────────────────────────────────────
  {
    room: "aufzug2",
    title: tr("Listening core"),
    idea: tr(
      "Perforated steel over acoustic foam: a diffuser wall of wells with different depths swallows every echo. The light listens too — it follows the lab's ambience like a slow meter.",
    ),
    wall: wall("acoustic", {
      panel: 8,
      pillar: 8,
      cornice: "chamfer",
      paint: { panel: "fabric_gray", seam: "line", accent: "paint_black", cap: "metal_dark" },
    }),
    floor: floor("rings", { paint: { a: "floor_dark", b: "metal_dark" } }),
    signature: sig(
      "aufzug2",
      tr("skin::Listening"),
      "#8b00ff",
      "#c38bff",
      "#1a1820",
      0,
      "reactive",
      1,
      0.8,
      "signal",
    ),
    alts: ["spectrum", "aurora", "night"],
    events: [tr("X0-R8T speaks: the wells pulse with the voice.")],
    ref: [9],
  },
  {
    room: "messgang",
    title: tr("Ruler"),
    idea: tr(
      "A measurement corridor with a graduated scale along both walls: fine ticks every fine voxel, long ticks every voxel, decade marks with node lights. A scan line measures the room from floor to cornice.",
    ),
    wall: wall("grid", {
      panel: 16,
      rows: 2,
      bands: [{ v0: 14, v1: 19, kind: "ruler" }],
      paint: { panel: "field", seam: "wall_dk", cap: "metal_dark" },
    }),
    floor: floor("guide", { tile: 8, lines: "sides", diamonds: true }),
    signature: sig("messgang", tr("Measure"), "#00ffff", "#ffb800", "#5b6068", 0, "scan", 0.5),
    alts: ["grid_blue", "work", "tunnel"],
    events: [tr("A measurement puzzle runs: the scan freezes at the answer.")],
    ref: [7],
  },
  {
    room: "signal",
    title: tr("VU wall"),
    idea: tr(
      "Quadratic-residue diffusers in two tones cover the walls; between them vertical light slits rise and fall like a VU meter with the music and the signal level. The floor is a dark plum with concentric rings around the listening spot.",
    ),
    wall: wall("acoustic", {
      panel: 12,
      cornice: "cove",
      paint: { panel: "fabric_gray", seam: "line", accent: "paint_black", cap: "metal_dark" },
    }),
    floor: floor("rings", { paint: { a: "floor_purple", b: "black" } }),
    signature: sig(
      "signal",
      tr("Spectrum"),
      "#ff00ff",
      "#00ffff",
      "#14101a",
      0,
      "meter",
      1,
      1,
      "signal",
      "#00ffff",
    ),
    alts: ["spectrum", "aurora", "phosphor", "night"],
    events: [tr("First answer of X0-R8T: every slit flashes white once.")],
    ref: [9],
  },
  {
    room: "anomalie",
    title: tr("Singing edges"),
    idea: tr(
      "Faceted shards of dark panelling meet in glowing edges, the way compression has edges. The edges flicker and twinkle violet, the floor cracks glow — the room sings when the Anomaly Detector is on.",
    ),
    wall: wall("facet", {
      panel: 12,
      cornice: "chamfer",
      paint: {
        panel: "floor_forge",
        seam: "line",
        accent: "field",
        dark: "black",
        cap: "metal_dark",
      },
    }),
    floor: floor("concrete", {
      tile: 32,
      cracks: true,
      paint: { a: "floor_forge", b: "black", grout: "black" },
    }),
    signature: sig(
      "anomalie",
      tr("Shimmer"),
      "#b060ff",
      "#ffffff",
      "#1c1a24",
      0.1,
      "twinkle",
      0.8,
      1,
      "clarity",
    ),
    alts: ["cathedral", "abyss", "aurora"],
    events: [tr("AND-001 detects: the edges flash in sequence toward the source.")],
    ref: [8],
  },
  {
    room: "diagnose",
    title: tr("Error code"),
    idea: tr(
      "A clean lab of white tiles with a blue signage band and a row of small diagnostic screens. One node in every screen bezel blinks the error code that has been blinking since 2019.",
    ),
    wall: wall("tile", {
      panel: 4,
      rows: 6,
      bands: [
        { v0: 14, v1: 15, kind: "light" },
        { v0: 17, v1: 23, kind: "duct" },
      ],
      paint: { panel: "tile_white", seam: "coat_shadow", cap: "metal_light" },
    }),
    floor: floor("tiles", {
      tile: 8,
      lines: "sides",
      paint: { a: "floor_tile", b: "tile_white_dk" },
    }),
    signature: sig(
      "diagnose",
      tr("Error code"),
      "#1f5fbf",
      "#ff3333",
      "#cfd3d6",
      0,
      "pulse",
      0.8,
      0.9,
    ),
    alts: ["work", "grid_blue", "cryo"],
    events: [tr("Diagnosis finished: the code turns green.")],
    ref: [],
  },
  {
    room: "hangar",
    title: tr("Runway"),
    idea: tr(
      "Concrete panels with hazard chevrons and painted bay numbers; on the floor a runway of guide lines and diamonds leads to the sealed shaft. When the drone launches, the lights chase toward the shaft.",
    ),
    wall: wall("plate", {
      panel: 32,
      rows: 2,
      relief: "flat",
      base: "hazard",
      inlays: 0.5,
      glyphs: "digits",
      paint: {
        panel: "concrete",
        seam: "concrete_dark",
        inlay: "safety_yellow",
        accent: "concrete_dark",
        cap: "concrete_dark",
      },
    }),
    floor: floor("guide", {
      tile: 32,
      lines: "both",
      diamonds: true,
      paint: { a: "concrete_dark", b: "concrete", grout: "asphalt" },
    }),
    signature: sig("hangar", tr("skin::Launch"), "#ffd400", "#ffffff", "#6e6e68", 0, "chase", 1),
    alts: ["work", "tunnel", "alarm"],
    events: [tr("EXD-001 launches: runway chase toward the shaft.")],
    ref: [7],
  },
  {
    room: "tresor",
    title: tr("Deposit boxes"),
    idea: tr(
      "Walls of square safe-deposit doors with brass keyholes; a gold cap and gold line. The keyholes twinkle like something inside is awake. The floor carries a gold diamond inlay.",
    ),
    wall: wall("drawers", {
      panel: 6,
      rows: 4,
      glyphs: "keyholes",
      paint: { panel: "field", seam: "line", accent: "node", cap: "gold" },
    }),
    floor: floor("tiles", {
      tile: 16,
      diamonds: true,
      paint: { a: "floor_forge", b: "black", grout: "brass" },
    }),
    signature: sig(
      "tresor",
      tr("Gold leaf"),
      "#e0b64a",
      "#fff0a0",
      "#120c00",
      0.05,
      "twinkle",
      0.5,
    ),
    alts: ["gold", "cathedral", "night"],
    events: [tr("A relic is taken: its keyhole stays lit.")],
    ref: [8],
  },
  {
    room: "botdepot",
    title: tr("Charging bays"),
    idea: tr(
      "Vertical bay frames with stencilled numbers and a charge bar in each; hazard baseboard, grate floor with bay lines. A reactivated bot's bar breathes green; a broken one stays dark.",
    ),
    wall: wall("rack", {
      panel: 16,
      base: "hazard",
      inlays: 0.5,
      glyphs: "digits",
      paint: {
        panel: "field",
        seam: "olive_dk",
        accent: "node",
        inlay: "safety_yellow",
        cap: "olive_dk",
      },
    }),
    floor: floor("grate", {
      lines: "both",
      paint: { a: "floor_grate", b: "black", border: "safety_green" },
    }),
    signature: sig("botdepot", tr("Charging"), "#1fa34a", "#00ff66", "#4a5040", 0, "breathe", 0.5),
    alts: ["load", "work", "night"],
    events: [tr("Bot service done: its bay flashes white.")],
    ref: [],
  },
  {
    room: "strahlengang",
    title: tr("Dosimeter"),
    idea: tr(
      "Lead-grey plates with radiation trefoils, a hazard base and a yellow line that clicks like a Geiger counter — irregular flicker that grows denser the closer the anomaly runs.",
    ),
    wall: wall("plate", {
      panel: 12,
      rows: 2,
      base: "hazard",
      inlays: 0.5,
      glyphs: "trefoil",
      bands: [{ v0: 15, v1: 16, kind: "light" }],
      paint: {
        panel: "steel_dark",
        seam: "metal_dark",
        inlay: "safety_yellow",
        accent: "chrome",
        cap: "metal_dark",
      },
    }),
    floor: floor("grate", { paint: { a: "floor_grate", b: "black", border: "safety_yellow" } }),
    signature: sig(
      "strahlengang",
      tr("Geiger"),
      "#ffd400",
      "#ffd400",
      "#50565d",
      0,
      "flicker",
      1.5,
    ),
    alts: ["alarm", "lemon", "work"],
    events: [tr("Anomaly active: the flicker speeds up.")],
    ref: [4],
  },
  {
    room: "studio",
    title: tr("skin::Tape"),
    idea: tr(
      "Damien's hidden studio: wooden diffusers and bass traps, a warm amber VU meter in the slits and a red carpet. The meter rises with whatever plays on the tape machines.",
    ),
    wall: wall("acoustic", {
      panel: 8,
      cornice: "cove",
      paint: { panel: "wood", seam: "line", accent: "wood_dark", cap: "walnut" },
    }),
    floor: floor("carpet", { paint: { a: "carpet_red", b: "fabric_red_shade", border: "walnut" } }),
    signature: sig(
      "studio",
      tr("VU amber"),
      "#ffaa00",
      "#ff3333",
      "#3a2618",
      0,
      "meter",
      1,
      1,
      "signal",
    ),
    alts: ["spectrum", "dawn", "night"],
    events: [tr("A song plays in the studio: the meter follows it.")],
    ref: [3],
  },

  // ── Ebene −3 ─────────────────────────────────────────────────────
  {
    room: "aufzug3",
    title: tr("Cerulean seep"),
    idea: tr(
      "Ribs with frost on their edges, a painted warning band on the floor, and cerulean light seeping up from the Forge: a scan rises from the floor through the ribs, slowly, like cold water.",
    ),
    wall: wall("rib", {
      panel: 16,
      rows: 3,
      pillar: 8,
      bands: [{ v0: 24, v1: 27, kind: "frost" }],
      cornice: "chamfer",
      paint: { panel: "field", seam: "metal_dark", accent: "line", cap: "metal_dark" },
    }),
    floor: floor("rings", { paint: { a: "floor_dark", b: "metal_dark", border: "safety_yellow" } }),
    signature: sig("aufzug3", tr("skin::Seep"), "#3fa7ff", "#cfe8ff", "#1c2028", 0.05, "scan", 0.3),
    alts: ["cryo", "grid_blue", "abyss"],
    events: [tr("Forge field on: the seep turns white-gold.")],
    ref: [9],
  },
  {
    room: "vorraum",
    title: tr("Pressure"),
    idea: tr(
      "Heavy plates under ice, a frost band and a pulse between red and blue while the pressure equalises. The warning sign is a glyph that glows through the ice.",
    ),
    wall: wall("plate", {
      panel: 12,
      rows: 2,
      inlays: 0.4,
      glyphs: "chevrons",
      bands: [{ v0: 20, v1: 27, kind: "frost" }],
      paint: { panel: "field", seam: "metal_dark", inlay: "line", accent: "chrome", cap: "ice" },
    }),
    floor: floor("grate", { paint: { a: "floor_grate", b: "ice" } }),
    signature: sig(
      "vorraum",
      tr("Equalise"),
      "#ff3020",
      "#3fd0ff",
      "#3d4147",
      0,
      "pulse",
      0.6,
      1,
      "none",
    ),
    alts: ["cryo", "alarm"],
    events: [tr("Pressure equalised: the pulse settles to blue.")],
    ref: [],
  },
  {
    room: "forge",
    title: tr("Field coils"),
    idea: tr(
      "Horizontal field coils wind around the chamber between faceted panels; the floor is a ring field around the two Synapsis stations. When the Infinity Forge field runs, ripples of cerulean travel outward from the centre.",
    ),
    wall: wall("grid", {
      panel: 12,
      rows: 2,
      pillar: 8,
      bands: [
        { v0: 8, v1: 11, kind: "coils" },
        { v0: 18, v1: 21, kind: "coils" },
      ],
      cornice: "chamfer",
      paint: { panel: "field", seam: "metal_dark", cap: "metal_dark" },
    }),
    floor: floor("rings", { paint: { a: "floor_forge", b: "black" } }),
    signature: sig(
      "forge",
      tr("Forge field"),
      "#3fa7ff",
      "#ffe9a8",
      "#0a1420",
      0.15,
      "ripple",
      0.6,
    ),
    alts: ["grid_blue", "aurora", "gold"],
    events: [tr("A forging completes: one white-gold ripple.")],
    ref: [9],
  },
  {
    room: "reaktor",
    title: tr("Cherenkov"),
    idea: tr(
      "Olive riveted plates around the plinth with its magnetic rings; the line is Cherenkov blue and breathes with the reactor's output. Hazard rings on the floor around the plinth.",
    ),
    wall: wall("plate", {
      panel: 16,
      rows: 3,
      base: "hazard",
      paint: { panel: "field", seam: "line", accent: "chrome", cap: "olive_dk" },
    }),
    floor: floor("rings", {
      paint: { a: "concrete_dark", b: "olive_dk", border: "safety_yellow" },
    }),
    signature: sig(
      "reaktor",
      tr("Cherenkov"),
      "#3fd0ff",
      "#e8f4ff",
      "#4a5040",
      0,
      "reactive",
      1,
      1,
      "power",
    ),
    alts: ["heat", "alarm", "grid_blue"],
    events: [tr("MFR-001 overload: Alarm until it cools down.")],
    ref: [],
  },
  {
    room: "containment",
    title: tr("Field cell"),
    idea: tr(
      "Black tiles with steel grout, a magenta field line that pulses; the floor is plum tile. If containment breaks, the room jumps to Alarm on its own.",
    ),
    wall: wall("tile", {
      panel: 4,
      rows: 6,
      bands: [
        { v0: 9, v1: 10, kind: "light" },
        { v0: 21, v1: 22, kind: "light" },
      ],
      paint: { panel: "tile_black", seam: "steel_dark", cap: "metal_dark" },
    }),
    floor: floor("tiles", {
      tile: 8,
      paint: { a: "floor_purple", b: "black", grout: "steel_dark" },
    }),
    signature: sig("containment", tr("Field"), "#ff3fbf", "#ff00ff", "#1c1e21", 0, "pulse", 0.5),
    alts: ["abyss", "alarm", "ink_red"],
    events: [tr("Breach: Alarm (forced) until EMC-001 holds again.")],
    ref: [],
  },
  {
    room: "rechenkern",
    title: tr("Neural grid"),
    idea: tr(
      "The blue grid room of ref 9: outlined rack panels, a lit cove, a diamond-inlaid floor. Data rain falls down the seams; its density is the compute core's load. Something here thinks.",
    ),
    wall: wall("rack", {
      panel: 8,
      bezel: true,
      cornice: "cove",
      paint: { panel: "field", seam: "line", accent: "node", cap: "metal_dark" },
    }),
    floor: floor("tiles", {
      tile: 16,
      diamonds: true,
      paint: { a: "floor_blue", b: "paint_navy", grout: "black" },
    }),
    signature: sig(
      "rechenkern",
      tr("Neural rain"),
      "#4ab8ff",
      "#bfe8ff",
      "#050a3a",
      0.25,
      "rain",
      0.8,
      1,
      "load",
    ),
    alts: ["grid_blue", "phosphor", "aurora"],
    events: [tr("AIC-001 wakes: the rain turns into a scan.")],
    ref: [9],
  },
  {
    room: "teleport",
    title: tr("Halo gate"),
    idea: tr(
      "Ribs every four voxels make the walls an octagonal tunnel around the circular plinth; rings and spokes on the floor. Exotic blue ripples run toward the plinth, faster the closer a jump is.",
    ),
    wall: wall("rib", {
      panel: 16,
      rows: 3,
      pillar: 4,
      cornice: "chamfer",
      paint: { panel: "field", seam: "black", accent: "line", cap: "metal_dark" },
    }),
    floor: floor("rings", { paint: { a: "floor_forge", b: "black" } }),
    signature: sig("teleport", tr("Halo"), "#4b3bff", "#c38bff", "#0a0820", 0.1, "ripple", 1),
    alts: ["tunnel", "grid_blue", "aurora"],
    events: [tr("Jump: the ripple reverses and collapses into the plinth.")],
    ref: [7, 9],
  },
  {
    room: "quanten",
    title: tr("Superposition"),
    idea: tr(
      "Teal tiles and a screen band of qubit readouts; nodes twinkle independently, never twice the same — the qubits don't forget, but they never decide either.",
    ),
    wall: wall("screen", {
      panel: 8,
      rows: 2,
      paint: { panel: "field", seam: "teal_dk", accent: "node", cap: "tile_teal" },
    }),
    floor: floor("tiles", {
      tile: 8,
      paint: { a: "tile_teal", b: "floor_blue", grout: "tile_black" },
    }),
    signature: sig("quanten", tr("Qubit"), "#5cf2ff", "#ffffff", "#0a2a30", 0.3, "twinkle", 1),
    alts: ["cryo", "aurora", "ink_teal"],
    events: [tr("Measurement: every node freezes for a second.")],
    ref: [6],
  },
  {
    room: "kaeltearchiv",
    title: tr("Hoarfrost"),
    idea: tr(
      "Shelves under hoarfrost: drawer fronts with a thick frost band, an ice-white field glow that breathes so slowly you only see it if you stand still.",
    ),
    wall: wall("drawers", {
      panel: 8,
      rows: 4,
      bands: [{ v0: 20, v1: 27, kind: "frost" }],
      paint: { panel: "field", seam: "steel_dark", accent: "aluminium", cap: "ice" },
    }),
    floor: floor("tiles", { tile: 16, paint: { a: "floor_blue", b: "ice", grout: "steel_dark" } }),
    signature: sig(
      "kaeltearchiv",
      tr("Hoarfrost"),
      "#cfefff",
      "#ffffff",
      "#9fb8c8",
      0.4,
      "breathe",
      0.08,
      0.8,
    ),
    alts: ["cryo", "night"],
    events: [],
    ref: [],
  },

  // ── Ebene −4 (Wohnebene) ─────────────────────────────────────────
  {
    room: "aufzug4",
    title: tr("Grow-light atrium"),
    idea: tr(
      "Beige wainscot with a wooden trellis band where the ivy climbs; a grow light in the cove follows the time of day — dawn pink, noon white, night off.",
    ),
    wall: wall("wainscot", {
      panel: 16,
      bands: [{ v0: 15, v1: 25, kind: "plants" }],
      cornice: "cove",
      dado: "tile",
      paint: { panel: "field", seam: "tile_cream_dk", cap: "walnut", dado: "tile_cream" },
    }),
    floor: floor("terrazzo", {
      paint: { a: "floor_beige", b: "beige_dk", grout: "floor_beige_dk" },
    }),
    signature: sig(
      "aufzug4",
      tr("Grow light"),
      "#ff8ad8",
      "#fff4c8",
      "#8a816c",
      0.1,
      "daylight",
      1,
      0.9,
      "clock",
    ),
    alts: ["dawn", "aurora", "night"],
    events: [],
    ref: [],
  },
  {
    room: "wohnflur",
    title: tr("Evening hall"),
    idea: tr(
      "Wainscot with a picture rail, a red carpet with a border, and a warm cove light that follows the evening. Name plates beside the doors glow softly.",
    ),
    wall: wall("wainscot", {
      panel: 12,
      cornice: "cove",
      dado: "board",
      paint: { panel: "field", seam: "wood_dark", cap: "walnut", dado: "wood" },
    }),
    floor: floor("carpet", { paint: { a: "carpet_red", b: "fabric_red_shade", border: "walnut" } }),
    signature: sig(
      "wohnflur",
      tr("Evening"),
      "#ffd9a0",
      "#ffb070",
      "#8a816c",
      0.05,
      "daylight",
      1,
      0.8,
      "clock",
    ),
    alts: ["dawn", "night", "work"],
    events: [],
    ref: [],
  },
  {
    room: "jadeq",
    title: tr("Colour-sorted"),
    idea: tr(
      "Jade's teal room: a teal pegboard full of pinned paper sketches — parts, brackets, half-ideas — and above it a narrow notebook shelf with spines sorted by colour, like her stacks. Warm reading cove, blue carpet. At night only the shelf's node lights stay on, dim.",
    ),
    wall: wall("pegboard", {
      panel: 10,
      rows: 2,
      base: "wood",
      inlays: 0.6,
      glyphs: "tetro",
      bands: [{ v0: 16, v1: 21, kind: "notebooks" }],
      cornice: "cove",
      paint: { panel: "field", seam: "teal_dk", inlay: "paper", cap: "walnut" },
    }),
    floor: floor("carpet", {
      paint: { a: "carpet_blue", b: "fabric_blue_shade", border: "walnut" },
    }),
    signature: sig(
      "jadeq",
      tr("skin::Reading"),
      "#ffd9a0",
      "#5cf2ff",
      "#2d6b6b",
      0.05,
      "daylight",
      1,
      0.85,
      "clock",
    ),
    alts: ["dawn", "night", "ink_teal"],
    events: [tr("Jade sleeps: Night watch until she wakes.")],
    ref: [6],
  },
  {
    room: "damienq",
    title: tr("Legal pads"),
    idea: tr(
      "Olive wainscot, and above it seventeen yellow legal pads pinned in a row, numbered — chaos with a system. The light swings with the grandfather clock that is missing a gear: a breath every two seconds, slightly off.",
    ),
    wall: wall("wainscot", {
      panel: 12,
      bands: [{ v0: 14, v1: 23, kind: "pads" }],
      cornice: "cove",
      dado: "bead",
      paint: { panel: "field", seam: "olive_dk", cap: "walnut", dado: "olive_lt" },
    }),
    floor: floor("carpet", {
      paint: { a: "carpet_green", b: "fabric_green_shade", border: "walnut" },
    }),
    signature: sig(
      "damienq",
      tr("Pendulum"),
      "#ffd9a0",
      "#ffaa00",
      "#4a5040",
      0,
      "breathe",
      0.53,
      0.8,
    ),
    alts: ["dawn", "ink_red", "night"],
    events: [tr("The clock is repaired: the breath falls exactly on the second.")],
    ref: [],
  },
  {
    room: "kantine",
    title: tr("Coffee break"),
    idea: tr(
      "Subway tiles, a checkered floor, a warm band over the counter. A node light near the coffee machine glows when it has power — from the wall, not the socket.",
    ),
    wall: wall("tile", {
      panel: 8,
      rows: 8,
      bands: [{ v0: 17, v1: 18, kind: "light" }],
      paint: { panel: "tile_white", seam: "coat_shadow", cap: "walnut" },
    }),
    floor: floor("checker", {
      tile: 8,
      paint: { a: "tile_white", b: "tile_black", grout: "steel_dark" },
    }),
    signature: sig(
      "kantine",
      tr("Coffee"),
      "#ffd9a0",
      "#ffb800",
      "#cfd3d6",
      0,
      "daylight",
      1,
      0.9,
      "clock",
    ),
    alts: ["work", "dawn", "night"],
    events: [tr("Coffee brewed: the node blinks three times.")],
    ref: [],
  },
  {
    room: "bibliothek",
    title: tr("Spines"),
    idea: tr(
      "Book spines from wainscot to cornice in real colours (red, green, blue, brown); a reading cove light and a basket-weave parquet. Static, warm, quiet — the light only dims when the room is empty.",
    ),
    wall: wall("wainscot", {
      panel: 12,
      bands: [
        { v0: 13, v1: 18, kind: "books" },
        { v0: 20, v1: 25, kind: "books" },
      ],
      cornice: "cove",
      paint: { panel: "field", seam: "wood_dark", cap: "walnut", dado: "wood_red" },
    }),
    floor: floor("parquet", { tile: 4, paint: { a: "oak", b: "wood_dark", grout: "walnut" } }),
    signature: sig(
      "bibliothek",
      tr("Reading lamp"),
      "#ffd9a0",
      "#ffb070",
      "#8a816c",
      0.05,
      "static",
      1,
      0.75,
    ),
    alts: ["dawn", "night", "ink_red"],
    events: [],
    ref: [],
  },
  {
    room: "gewaechshaus",
    title: tr("Photosynthesis"),
    idea: tr(
      "Glass panes in steel mullions over planter beds; the grow light in the cove follows the day, and glow-algae nodes in the bed rims breathe green. The floor is beds and stepping-stone paths.",
    ),
    wall: wall("glass", {
      panel: 12,
      rows: 2,
      cornice: "cove",
      paint: { panel: "glass_green", seam: "steel", accent: "node", cap: "steel_dark" },
    }),
    floor: floor("beds", {
      tile: 24,
      paint: { a: "soil", b: "floor_green", grout: "wood_dark", node: "node" },
    }),
    signature: sig(
      "gewaechshaus",
      tr("Photosynthesis"),
      "#ff5fd0",
      "#39ff88",
      "#2f3b33",
      0,
      "daylight",
      1,
      1,
      "clock",
    ),
    alts: ["aurora", "dawn", "night"],
    events: [tr("Plants watered: the algae nodes flare.")],
    ref: [],
  },
  {
    room: "gartengang",
    title: tr("Mint wins"),
    idea: tr(
      "A wainscot passage with a cable duct band where mint has taken over — leaves spill over the duct edge. The duct's light breathes green.",
    ),
    wall: wall("wainscot", {
      panel: 12,
      bands: [{ v0: 17, v1: 22, kind: "plants" }],
      cornice: "cove",
      dado: "bead",
      paint: { panel: "field", seam: "paint_mint_dk", cap: "walnut", dado: "paint_mint" },
    }),
    floor: floor("carpet", {
      paint: { a: "carpet_green", b: "fabric_green_shade", border: "walnut" },
    }),
    signature: sig(
      "gartengang",
      tr("Mint"),
      "#7dffb0",
      "#39ff88",
      "#8a816c",
      0,
      "breathe",
      0.3,
      0.8,
    ),
    alts: ["dawn", "night"],
    events: [],
    ref: [],
  },
  {
    room: "observatorium",
    title: tr("Dome segments"),
    idea: tr(
      "Steel dome segments as ribs, navy fields between them full of star nodes that twinkle; the floor is a star chart with rings and spokes. The strip of starlight through the gap becomes a slow scan.",
    ),
    wall: wall("rib", {
      panel: 16,
      rows: 3,
      pillar: 6,
      cornice: "chamfer",
      paint: { panel: "field", seam: "steel_dark", accent: "brass", cap: "brass" },
    }),
    floor: floor("stars", { paint: { a: "floor_dark", b: "paint_navy", grout: "brass" } }),
    signature: sig(
      "observatorium",
      tr("Starlight"),
      "#3a4a8a",
      "#ffffff",
      "#02030a",
      0,
      "twinkle",
      0.5,
    ),
    alts: ["starlight", "aurora", "grid_blue"],
    events: [tr("Dome opens: the field turns to sky blue, the stars fade.")],
    ref: [9],
  },
  {
    room: "funkraum",
    title: tr("Morse"),
    idea: tr(
      "Acoustic panels and, at eye height, the chalk Morse line from the wall — dots and dashes as node lights that play the code over and over as a chase.",
    ),
    wall: wall("acoustic", {
      panel: 8,
      bands: [{ v0: 14, v1: 16, kind: "morse" }],
      paint: {
        panel: "fabric_gray",
        seam: "paint_black",
        accent: "paint_black",
        cap: "metal_dark",
      },
    }),
    floor: floor("carpet", {
      paint: { a: "floor_purple", b: "carpet_blue", border: "metal_dark" },
    }),
    signature: sig("funkraum", tr("Morse"), "#ffaa00", "#ffaa00", "#2e2838", 0, "chase", 0.4),
    alts: ["phosphor", "spectrum", "night"],
    events: [tr("A transmission arrives: the code changes to the received one.")],
    ref: [],
  },

  // ── Ebene −5 (Schacht) ───────────────────────────────────────────
  {
    room: "aufzug5",
    title: tr("Miner's lamp"),
    idea: tr(
      "Raw rock with timber supports, rails in the gravel. Lamps on the timbers flicker like carbide light; thin crystal veins in the rock glow cyan.",
    ),
    wall: wall("rock", {
      pillar: 6,
      paint: { panel: "rock", seam: "rock_dark", accent: "wood", cap: "rock_dark" },
    }),
    floor: floor("gravel", {
      lines: "center",
      paint: { a: "asphalt", b: "rock_dark", line: "steel" },
    }),
    signature: sig(
      "aufzug5",
      tr("Carbide"),
      "#ffd9a0",
      "#45f0d8",
      "#4d4841",
      0,
      "flicker",
      0.3,
      0.8,
    ),
    alts: ["emergency", "abyss"],
    events: [],
    ref: [],
  },
  {
    room: "sohle",
    title: tr("Trickle"),
    idea: tr(
      "Rock with chalk marks, puddles on the floor. Somewhere it always trickles: cyan drops of light run down the veins.",
    ),
    wall: wall("rock", {
      paint: { panel: "rock", seam: "rock_dark", accent: "paper", cap: "rock_dark" },
    }),
    floor: floor("gravel", { cracks: true, paint: { a: "concrete_dark", b: "puddle" } }),
    signature: sig("sohle", tr("Trickle"), "#45f0d8", "#45f0d8", "#4d4841", 0, "rain", 0.3),
    alts: ["abyss", "emergency"],
    events: [],
    ref: [],
  },
  {
    room: "x9kammer",
    title: tr("Halo dust"),
    idea: tr(
      "Fine faceted panels full of glitter: the dust that never settles. Thousands of tiny white-gold nodes twinkle in the facets and on the floor — read under a microscope: THE HALO EXPANDS.",
    ),
    wall: wall("facet", {
      panel: 8,
      paint: {
        panel: "floor_forge",
        seam: "line",
        accent: "node",
        dark: "black",
        cap: "metal_dark",
      },
    }),
    floor: floor("terrazzo", {
      paint: { a: "floor_forge", b: "black", grout: "black", node: "node" },
    }),
    signature: sig("x9kammer", tr("Halo dust"), "#ffe9a8", "#fff4c8", "#1c1a24", 0, "twinkle", 1),
    alts: ["gold", "starlight", "cathedral"],
    events: [],
    ref: [8],
  },
  {
    room: "stollen",
    title: tr("Warm wall"),
    idea: tr(
      "A half-buried tunnel: rock, timber, bent rails. The walls are warm — orange heat breathes in the cracks, stronger toward the borehole.",
    ),
    wall: wall("rock", {
      cracks: true,
      pillar: 6,
      paint: { panel: "rock", seam: "rock_dark", accent: "wood", cap: "rock_dark" },
    }),
    floor: floor("gravel", {
      lines: "center",
      cracks: true,
      paint: { a: "asphalt", b: "rock_dark", line: "steel" },
    }),
    signature: sig(
      "stollen",
      tr("Warm wall"),
      "#ff6b00",
      "#ff4a1a",
      "#4d4841",
      0,
      "breathe",
      0.25,
      1,
      "heat",
    ),
    alts: ["heat", "emergency"],
    events: [],
    ref: [8],
  },
  {
    room: "hoehle",
    title: tr("Two shadows"),
    idea: tr(
      "The crystal cathedral of ref 8, in voxels: big faceted shards with glowing edges, the floor cracked and lit from below. The light cycles between violet and cyan and ripples outward — every shard casts two shadows.",
    ),
    wall: wall("facet", {
      panel: 10,
      cornice: "chamfer",
      paint: { panel: "rock_dark", seam: "line", accent: "field", dark: "black", cap: "rock_dark" },
    }),
    floor: floor("gravel", { cracks: true, paint: { a: "floor_purple", b: "rock_dark" } }),
    signature: sig(
      "hoehle",
      tr("Two shadows"),
      "#9d5cff",
      "#45f0d8",
      "#3a1a5c",
      0.35,
      "cycle",
      1,
      1,
      "clarity",
      "#45f0d8",
    ),
    alts: ["cathedral", "aurora", "abyss"],
    events: [tr("The membrane listens: one ripple from the centre.")],
    ref: [8],
  },
  {
    room: "c8versteck",
    title: tr("[EXTERNAL]"),
    idea: tr(
      "An improvised server room: rack fronts from three decades, mismatched, cables everywhere. Phosphor-green rain runs down the seams, and every few seconds one rack spells [EXTERNAL].",
    ),
    wall: wall("rack", {
      panel: 12,
      paint: { panel: "field", seam: "line", accent: "node", cap: "metal_dark" },
      bands: [{ v0: 22, v1: 26, kind: "cables" }],
    }),
    floor: floor("raised", { tile: 8, paint: { a: "floor_blue", b: "metal_dark" } }),
    signature: sig("c8versteck", tr("[EXTERNAL]"), "#33ff33", "#b8ffb8", "#0a1a0a", 0.1, "rain", 1),
    alts: ["phosphor", "load", "night"],
    events: [tr("C8-BR41N speaks: the rain stops, one line glows.")],
    ref: [],
  },
  {
    room: "truemmer",
    title: tr("Collapse"),
    idea: tr(
      "Olive plates, half of them fallen: rock shows through the gaps. Only emergency light still works, a dim red breath on the nodes.",
    ),
    wall: wall("plate", {
      panel: 16,
      rows: 2,
      dark: 3,
      nodes: true,
      paint: {
        panel: "wall_olive",
        seam: "olive_dk",
        dark: "rock",
        accent: "chrome",
        cap: "rock_dark",
      },
    }),
    floor: floor("gravel", { cracks: true, paint: { a: "concrete_dark", b: "rock" } }),
    signature: sig(
      "truemmer",
      tr("Emergency"),
      "#000000",
      "#ff3020",
      "#4a5040",
      0,
      "breathe",
      0.3,
      0.5,
    ),
    alts: ["emergency", "abyss"],
    events: [],
    ref: [],
  },
  {
    room: "bohrung",
    title: tr("847 m"),
    idea: tr(
      "Formwork concrete with a ring of copper pipe; the floor rings around the drill head. Heat light scans downward, toward the boiling rock 847 metres below.",
    ),
    wall: wall("plate", {
      panel: 32,
      rows: 2,
      relief: "flat",
      cracks: true,
      crackGlow: "node",
      bands: [{ v0: 10, v1: 12, kind: "pipes" }],
      paint: {
        panel: "concrete",
        seam: "concrete_dark",
        accent: "concrete_dark",
        cap: "concrete_dark",
      },
    }),
    floor: floor("rings", { cracks: true, paint: { a: "concrete_dark", b: "asphalt" } }),
    signature: sig(
      "bohrung",
      tr("Downward"),
      "#ff6b00",
      "#ff4a1a",
      "#55554f",
      0,
      "scan",
      0.3,
      1,
      "heat",
    ),
    alts: ["heat", "emergency"],
    events: [],
    ref: [8],
  },
];

const BY_ROOM = new Map(ROOM_SKINS.map((s) => [s.room, s]));

export function roomSkin(room: string): RoomSkin | undefined {
  return BY_ROOM.get(room);
}
