/**
 * Measure every song (first 90 s, offline) and write the loudness table the
 * player uses to even out levels between songs and genres.
 *
 *   node_modules/.bin/vite-node --config scripts/audio/vite.config.mjs scripts/audio/loudness.ts
 *
 * Re-run after adding or changing songs (tests/world/songs.test.ts checks
 * that every song has an entry).
 */
import fs from "node:fs";
import path from "node:path";
import { SONGS } from "@/lib/world/audio/songs/catalog";
import { levelStats, renderSong } from "@/lib/world/audio/songs/offline";

const out = path.resolve(process.cwd(), "lib/world/audio/songs/loudness.ts");
const rows: string[] = [];
for (const s of SONGS) {
  const r = renderSong(s, { sampleRate: 8000, maxSeconds: 90, hall: false, tail: 0 });
  const st = levelStats(r, 2);
  // Loudness = mean of the louder half of the 2-second windows (ignores intros / breakdowns).
  const w = [...st.windows].sort((a, b) => b - a);
  const top = w.slice(0, Math.max(1, Math.floor(w.length / 2)));
  const rms = top.reduce((n, x) => n + x, 0) / top.length;
  rows.push(`  ${s.id}: ${rms.toFixed(4)},`);
  console.log(s.id.padEnd(34), rms.toFixed(4));
}
fs.writeFileSync(
  out,
  `/**
 * Measured loudness per song (RMS of the louder half, offline render, no hall).
 * GENERATED by scripts/audio/loudness.ts — re-run after changing songs.
 */
export const SONG_LOUDNESS: Readonly<Record<string, number>> = {
${rows.join("\n")}
};
`,
);
console.log(`wrote ${out}`);
