/**
 * Electronic — the lab's machines singing: server rooms, the MCP core,
 * _unOS boot sequences, network hubs and power grids.
 * Composing guide: lib/world/audio/songs/COMPOSING.md.
 */
import { tr } from "@/lib/i18n";
import type { SongDef } from "@/lib/world/audio/songs/types";

export const ELECTRONIC: readonly SongDef[] = [
  // ── 1 · chiptune adventure, A dorian ─────────────────────────────
  {
    id: "electronic_boot_sequence",
    title: tr("song::Boot Sequence"),
    genre: "electronic",
    blurb: tr("_unOS wakes up line by line; a chip theme counts the modules as they load."),
    bpm: 124,
    key: 69,
    mode: "dorian",
    handshake: true,
    voices: {
      lead: "chip",
      leadAlt: "celesta",
      counter: "synthlead",
      bell: "celesta",
      arp: "pluck",
      pad: "glass",
      bass: "chipbass",
      kit: "chip",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "1 1 4 4",
        arp: "pulse",
        pad: "swell",
        bass: "pulse",
        drums: "tick",
        energy: 0.3,
      },
      A: {
        bars: 8,
        chords: "1 7 4 1 1 7 4 5",
        lead: "1':2 5 1' 3':2 2':2 | 7:2 5 7 2':4 | 6:2 4 6 1':2 6:2 | 5:6 -:2 | 1':2 5 1' 3':2 5':2 | 4':2 3' 2' 7:4 | 6:2 1' 2' 4':3 3' | 2':4 5:4",
        arp: "up",
        pad: "offbeat",
        bass: "octave",
        drums: "electro",
        energy: 0.6,
      },
      B: {
        bars: 8,
        chords: "3 4 5 1 3 4 7 7",
        lead: "3:3 5:3 7:2 | 6:3 1':3 6:2 | 7:3 5:3 2:2 | 1:6 -:2 | 3':3 1':3 5:2 | 2':3 1':3 6:2 | 7:2 2' 4' 2':2 7:2 | 7:4 -:4",
        counter: "5,:8 | 4,:8 | 5,:8 | 3,:8 | 5,:8 | 4,:8 | 4,:8 | 2,:8",
        arp: "broken",
        pad: "hold",
        bass: "drive",
        drums: "electro",
        energy: 0.7,
      },
      C: {
        bars: 8,
        chords: "4 4 1 1 7 7 5 5",
        lead: "1':8 | 6:4 4:4 | 5:8 | 3:4 1:4 | 2:8 | 7,:4 2:4 | 5:8 | _:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.28,
      },
      D: {
        bars: 8,
        chords: "4 5 1 1 4 5 7 7",
        lead: "6 6 1' 6 2':2 1':2 | 7 7 2' 7 3':2 2':2 | 1' 1' 3' 1' 5':2 3':2 | 5':4 4':2 3':2",
        arp: "cascade",
        pad: "pulse",
        bass: "arp",
        drums: "break",
        energy: 0.62,
        fill: true,
      },
      outro: {
        bars: 4,
        chords: "1 7 4 1",
        arp: "up",
        pad: "swell",
        bass: "hold",
        drums: "tick",
        energy: 0.25,
      },
    },
    form: ["intro", "A", "A", "B", "A", "C", "D", "A", "A", "B", "B", "C", "D", "A", "A", "outro"],
  },

  // ── 2 · minimal techno pulse, Bb phrygian ────────────────────────
  {
    id: "electronic_mcp_core_pulse",
    title: tr("song::MCP Core Pulse"),
    genre: "electronic",
    blurb: tr("Four on the floor under the core; the MCP thinks in a flattened second."),
    bpm: 128,
    key: 70,
    mode: "phrygian",
    voices: {
      lead: "synthlead",
      leadAlt: "chip",
      counter: "pluck",
      arp: "chip",
      pad: "darkpad",
      bass: "fmbass",
      kit: "electro",
    },
    sections: {
      intro: {
        bars: 8,
        chords: "1",
        arp: "pulse",
        pad: "none",
        bass: "pulse",
        drums: "four",
        energy: 0.4,
      },
      A: {
        bars: 8,
        chords: "1 . 2 1 1 . 7 1",
        lead: "1' - 1' 2' -:2 1' 5 | -:2 3 4 5:4 | 2' - 2' 3' -:2 2' 6 | -:2 5 4 3:2 1:2 | 1' - 1' 2' -:2 1' 5 | -:2 3' 4' 5':4 | 7:2 4' 3' 2':2 7:2 | 1':6 -:2",
        arp: "pulse",
        pad: "offbeat",
        bass: "drive",
        drums: "four",
        energy: 0.62,
      },
      B: {
        bars: 8,
        chords: "6 3 7 1 6 3 2 2",
        lead: "3':4 2':2 1':2 | 5:4 6:2 5:2 | 4:6 7:2 | 1':8 | 3':4 4':2 5':2 | 6':4 5':2 4':2 | 3':3 2':3 6:2 | 2':8",
        arp: "updown",
        pad: "hold",
        bass: "octave",
        drums: "four",
        energy: 0.72,
      },
      C: {
        bars: 8,
        chords: "1 2",
        lead: "5:6 3:2 | 6:8 | 5:4 4:3 3 | 2:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.3,
      },
      D: {
        bars: 8,
        chords: "1 . 7 . 6 . 2 .",
        lead: "1' 5 3' 1' 5 1' 3':2 | 1' 5 3' 1' 5 1' 5':2 | 7 4' 2' 7 4' 7 2':2 | 7 4' 2' 7 4' 7 4':2 | 6 1' 3' 6 1' 3' 1':2 | 6 1' 3' 6 1' 3' 5':2 | 2' 4' 6' 2' 4' 6' 4':2 | 2':8",
        arp: "pulse",
        pad: "stab",
        bass: "sync",
        drums: "electro",
        energy: 0.8,
        fill: true,
      },
      outro: {
        bars: 8,
        chords: "1",
        arp: "pulse",
        pad: "swell",
        bass: "pulse",
        drums: "four",
        energy: 0.35,
      },
    },
    form: [
      "intro",
      "A",
      "A",
      "B",
      "A",
      "A",
      "C",
      "C",
      "D",
      "D",
      "B",
      "A",
      "C",
      "D",
      "D",
      "A",
      "A",
      "outro",
    ],
  },

  // ── 3 · synthwave, C lydian ──────────────────────────────────────
  {
    id: "electronic_cerulean_overdrive",
    title: tr("song::Cerulean Overdrive"),
    genre: "electronic",
    blurb: tr("Synthwave in the colour of the crystal glow; the raised fourth shines like 490 nm."),
    bpm: 112,
    key: 72,
    mode: "lydian",
    voices: {
      lead: "synthlead",
      leadAlt: "celesta",
      counter: "strings",
      bell: "celesta",
      arp: "pluck",
      pad: "warmpad",
      bass: "synthbass",
      kit: "electro",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "1 2 1 2",
        arp: "up",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.3,
      },
      A: {
        bars: 8,
        chords: "1 2 3 6 1 2 5 5",
        lead: "5:3 3:3 1:2 | 2:3 4:3 6:2 | 7:3 5:2 3:3 | 1':6 6:2 | 5:3 3:3 5:2 | 6:3 4:2 2':3 | 2':4 7:2 5:2 | 5:6 -:2",
        arp: "up",
        pad: "hold",
        bass: "octave",
        drums: "break",
        energy: 0.6,
      },
      B: {
        bars: 8,
        chords: "6 5 2 1 6 7 2 2",
        lead: "3':2 2':2 1':2 6:2 | 7:4 5:4 | 6:2 4:2 2:2 4:2 | 3:8 | 6:2 1' 3' 5':4 | 4':2 2':2 7:4 | 6:3 4':3 2':2 | 2':8",
        counter: "1:8 | 7,:8 | 6,:8 | 5,:8 | 1:8 | 2:8 | 4:8 | 4:8",
        arp: "updown",
        pad: "hold",
        bass: "drive",
        drums: "electro",
        energy: 0.72,
      },
      C: {
        bars: 8,
        chords: "1 5 6 3 1 5 2 2",
        lead: "1':1.5 7:1.5 5 3:1.5 5:1.5 1' | 2':1.5 1':1.5 7 5:4 | 1':1.5 7:1.5 6 3:1.5 6:1.5 1' | 7:4 -:4 | 3':1.5 2':1.5 1' 5:1.5 1':1.5 3' | 5':4 4':2 2':2 | 2':3 1' 7:2 6:2 | 6:8",
        arp: "cascade",
        pad: "stab",
        bass: "sync",
        drums: "four",
        energy: 0.8,
      },
      D: {
        bars: 8,
        chords: "1 2 1 2",
        lead: "5:8 | 4:6 2:2 | 3:8 | 2:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.25,
      },
      outro: {
        bars: 4,
        chords: "1 2 1 1",
        arp: "up",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.2,
      },
    },
    form: ["intro", "A", "A", "B", "A", "C", "C", "B", "D", "A", "C", "C", "D", "A", "A", "outro"],
  },

  // ── 4 · chiptune adventure, G mixolydian ─────────────────────────
  {
    id: "electronic_unproc_wanderer",
    title: tr("song::Wandering /unproc"),
    genre: "electronic",
    blurb: tr("A chip-tune quest through procfs: every directory a room, every PID a friend."),
    bpm: 138,
    key: 67,
    mode: "mixolydian",
    voices: {
      lead: "chip",
      leadAlt: "ocarina",
      counter: "pluck",
      bell: "celesta",
      arp: "chip",
      pad: "glass",
      bass: "chipbass",
      kit: "chip",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "1 7 4 1",
        lead: "1' - 1' - 1':2 2':2 | 7:8 | 4':4 5':4 | 5':8",
        arp: "up",
        pad: "swell",
        bass: "pulse",
        drums: "tick",
        energy: 0.35,
      },
      A: {
        bars: 8,
        chords: "1 7 4 1 1 7 4-5 1",
        lead: "1' 5 1' 2' 3':2 1':2 | 7:2 4' 3' 2':3 - | 4' 3' 4' 5' 6':2 5':2 | 5':4 3':2 -:2 | 1' 5 1' 2' 3':2 5':2 | 6':2 7' 6' 4':2 2':2 | 4':2 3':2 2':2 7:2 | 1':6 -:2",
        arp: "up",
        pad: "offbeat",
        bass: "arp",
        drums: "break",
        energy: 0.65,
      },
      B: {
        bars: 8,
        chords: "6 2 4 5 6 2 7 7",
        lead: "3:2 5 6 5:2 3 2 | 2:3 3 4:4 | 5:2 4 3 4:2 6:2 | 5:6 -:2 | 6:2 5 6 3':2 1':2 | 2':3 1' 6:4 | 7:2 6 7 1':2 2':2 | 4':6 -:2",
        arp: "broken",
        pad: "pulse",
        bass: "octave",
        drums: "gallop",
        energy: 0.7,
      },
      C: {
        bars: 8,
        chords: "5 5 4 4 6 6 7 7",
        lead: "5:4 7:2 2':2 | 4':3 2':3 7:2 | 4:4 6:2 1':2 | 6:6 -:2 | 6:4 1':2 3':2 | 5':3 3':3 1':2 | 7:4 2':2 4':2 | 2':8",
        arp: "pulse",
        pad: "hold",
        bass: "sync",
        drums: "half",
        energy: 0.5,
      },
      D: {
        bars: 8,
        chords: "1 7 4 1",
        lead: "5:8 | 4:4 2:4 | 6:8 | 5:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.3,
      },
      outro: {
        bars: 4,
        chords: "4 7 1 1",
        lead: "4':4 3':4 | 2':4 7:4 | 1':8 | _:8",
        arp: "up",
        pad: "swell",
        bass: "hold",
        drums: "tick",
        energy: 0.3,
      },
    },
    form: [
      "intro",
      "A",
      "A",
      "B",
      "B",
      "A",
      "C",
      "C",
      "D",
      "A",
      "A",
      "B",
      "B",
      "C",
      "D",
      "A",
      "A",
      "outro",
    ],
  },

  // ── 5 · drum & bass, E harmonic minor ────────────────────────────
  {
    id: "electronic_brownout_protocol",
    title: tr("song::Brownout Protocol"),
    genre: "electronic",
    blurb: tr("The grid sags, the breakbeats race; a leading tone that refuses to go dark."),
    bpm: 140,
    key: 76,
    mode: "harmonic",
    voices: {
      lead: "synthlead",
      leadAlt: "chip",
      counter: "strings",
      arp: "pluck",
      pad: "darkpad",
      bass: "fmbass",
      kit: "electro",
    },
    sections: {
      intro: {
        bars: 8,
        chords: "1 1 6 5",
        arp: "pulse",
        pad: "swell",
        bass: "hold",
        drums: "tick",
        energy: 0.35,
      },
      A: {
        bars: 8,
        chords: "1 6 4 5 1 6 b7 5",
        lead: "1:2 5, 1 3 5 3 1 | 6:3 5 3:2 1:2 | 4:2 1 4 6:2 4:2 | 5:4 7:3 - | 1':2 7 1' 5:2 3:2 | 6:2 5 6 1':2 3':2 | 2':3 1' b7:2 4:2 | 7:6 -:2",
        arp: "cascade",
        pad: "hold",
        bass: "sync",
        drums: "dnb",
        energy: 0.7,
      },
      B: {
        bars: 8,
        chords: "6 b7 1 1 6 b7 5 5",
        lead: "3':6 1':2 | 2':6 b7:2 | 1':4 5:4 | 3:8 | 6:4 1':2 3':2 | 4':4 2':2 b7:2 | 2':3 7:3 5:2 | 5:8",
        counter: "3:8 | 4:8 | 5:8 | 1:8 | 3:8 | 4:8 | 7,:8 | 2:8",
        arp: "updown",
        pad: "swell",
        bass: "octave",
        drums: "dnb",
        energy: 0.78,
      },
      C: {
        bars: 8,
        chords: "4 5 1 6",
        lead: "1':4 6:4 | 7:8 | 5:4 3:4 | 1':8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.28,
      },
      D: {
        bars: 8,
        chords: "4 4 5 5 6 6 5 5",
        lead: "4 6 1' 4 6 1' 4 6 | 1' 4 6 1' 3':4 | 5 7 2' 5 7 2' 5 7 | 2' 5 7 2' 4':4 | 6 1' 3' 6 1' 3' 6 1' | 3' 1' 6 3' 1':4 | 5 7 2' 5 7 2' 5 7 | 2':4 7:4",
        arp: "up",
        pad: "pulse",
        bass: "arp",
        drums: "break",
        energy: 0.62,
        fill: true,
      },
      outro: {
        bars: 4,
        chords: "1 6 5 1",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.2,
      },
    },
    form: [
      "intro",
      "A",
      "A",
      "B",
      "B",
      "A",
      "C",
      "D",
      "A",
      "A",
      "B",
      "B",
      "C",
      "D",
      "D",
      "A",
      "A",
      "outro",
    ],
  },

  // ── 6 · handshake electronica, D aeolian ─────────────────────────
  {
    id: "electronic_handshake_3648",
    title: tr("song::Handshake 3-6-4-8"),
    genre: "electronic",
    blurb: tr("Celesta over synths spells the lab's handshake until the machines answer back."),
    bpm: 120,
    key: 74,
    mode: "aeolian",
    handshake: true,
    voices: {
      lead: "celesta",
      leadAlt: "chip",
      counter: "chip",
      bell: "musicbox",
      arp: "pluck",
      pad: "glass",
      bass: "fmbass",
      kit: "electro",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "6 4 1 1",
        arp: "pulse",
        pad: "swell",
        bass: "hold",
        drums: "tick",
        energy: 0.3,
      },
      A: {
        bars: 8,
        chords: "6 4 1 7 6 4 5 1",
        lead: "3:2 6:2 4:2 1':2 | 7:3 6 4:4 | 5:2 1':2 3':2 1':2 | 7:6 -:2 | 3:2 6:2 4:2 1':2 | 4':3 2' 1':2 6:2 | 7:2 1' 7 5:4 | 1:8",
        arp: "up",
        pad: "hold",
        bass: "sync",
        drums: "break",
        energy: 0.6,
      },
      B: {
        bars: 8,
        chords: "3 7 4 5 3 7 6 5",
        lead: "3':1.5 1':1.5 7 1':2 5:2 | 7:1.5 4:1.5 2 4:4 | 6:1.5 4:1.5 2 4:2 6:2 | 5:6 -:2 | 3':1.5 1':1.5 7 1':2 3':2 | 4':1.5 3':1.5 2' 7:4 | 6:1.5 1':1.5 3' 4':2 3':2 | 2':8",
        arp: "updown",
        pad: "offbeat",
        bass: "sync",
        drums: "four",
        energy: 0.72,
      },
      C: {
        bars: 8,
        chords: "3 6 4 1",
        lead: "3:8 | 6:8 | 4:8 | 1':8 | 3':6 2':2 | 6:6 7:2 | 4':6 5':2 | 1':8",
        counter:
          "3, 5, 7, 5, 3, 5, 7, 5, | 6, 1 3 1 6, 1 3 1 | 4, 6, 1 6, 4, 6, 1 6, | 1 3 5 3 1 3 5 3",
        arp: "pulse",
        pad: "hold",
        bass: "hold",
        drums: "half",
        energy: 0.45,
      },
      D: {
        bars: 8,
        chords: "1 6 4 5",
        lead: "5:6 3:2 | 3:4 1:4 | 4:6 6:2 | 5:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.25,
      },
      outro: {
        bars: 4,
        chords: "6 4 1 1",
        lead: "3:2 6:2 4:2 1':2 | -:8 | 1:8 | _:8",
        arp: "pulse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.22,
      },
    },
    form: [
      "intro",
      "A",
      "A",
      "B",
      "A",
      "C",
      "C",
      "B",
      "B",
      "A",
      "A",
      "B",
      "B",
      "D",
      "A",
      "A",
      "outro",
    ],
  },

  // ── 7 · downtempo electronica, B dorian ──────────────────────────
  {
    id: "electronic_halo_lattice",
    title: tr("song::Halo Lattice"),
    genre: "electronic",
    blurb: tr(
      "An ocarina drifts through the Halo crystal's lattice while slow machines keep time.",
    ),
    bpm: 108,
    key: 71,
    mode: "dorian",
    swing: 0.12,
    voices: {
      lead: "ocarina",
      leadAlt: "celesta",
      counter: "pluck",
      bell: "musicbox",
      arp: "pluck",
      pad: "glass",
      bass: "fmbass",
      kit: "electro",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "1 4 1 4",
        arp: "pulse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.25,
      },
      A: {
        bars: 8,
        chords: "1 4 3 7 1 4 7 4",
        lead: "5:3 1':3 7:2 | 6:4 5:2 4:2 | 5:3 3:3 1:2 | 2:6 -:2 | 5:3 1':3 2':2 | 3':3 2':2 1' 6:2 | 7:3 5:3 4:2 | 4:6 -:2",
        arp: "pulse",
        pad: "hold",
        bass: "dub",
        drums: "half",
        energy: 0.5,
      },
      B: {
        bars: 8,
        chords: "3 5 7 4 3 5 7 7",
        lead: "3':4 2':2 1':2 | 7:4 5:4 | 4:2 5:2 7:2 2':2 | 1':6 -:2 | 3':2 5':2 4':2 3':2 | 2':4 1':2 7:2 | 7:3 2':3 4':2 | 2':8",
        arp: "updown",
        pad: "hold",
        bass: "sync",
        drums: "break",
        energy: 0.62,
      },
      C: {
        bars: 8,
        chords: "1 2 3 2",
        lead: "5:2 4 3 1:4 | 6:2 5 4 2:4 | 7:2 6 5 3:4 | 2:8",
        arp: "cascade",
        pad: "swell",
        bass: "hold",
        drums: "half",
        energy: 0.45,
      },
      D: {
        bars: 8,
        chords: "4 1",
        lead: "6:8 | 5:8 | 4:6 2:2 | 1:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.25,
      },
      outro: {
        bars: 4,
        chords: "1 4 1 1",
        lead: "5:3 1':3 7:2 | 6:8 | 5:8 | _:8",
        arp: "pulse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.2,
      },
    },
    form: ["intro", "A", "A", "B", "A", "C", "C", "B", "B", "D", "A", "B", "A", "A", "outro"],
  },

  // ── 8 · network hub, F aeolian ───────────────────────────────────
  {
    id: "electronic_packet_storm",
    title: tr("song::Packet Storm"),
    genre: "electronic",
    blurb: tr("The network hub floods with packets from 2019; the kernel routes every one."),
    bpm: 132,
    key: 77,
    mode: "aeolian",
    voices: {
      lead: "chip",
      leadAlt: "synthlead",
      counter: "pluck",
      bell: "celesta",
      arp: "pluck",
      pad: "darkpad",
      bass: "synthbass",
      kit: "chip",
    },
    sections: {
      intro: {
        bars: 4,
        chords: "1 1 6 7",
        arp: "up",
        pad: "swell",
        bass: "pulse",
        drums: "tick",
        energy: 0.35,
      },
      A: {
        bars: 8,
        chords: "1 6 3 7 1 6 7 7",
        lead: "1 1 5, 1 3 1 5,:2 | 6, 6, 1 6, 3:2 1:2 | 3 3 1 3 5:2 3:2 | 2:4 7,:2 -:2 | 1 1 5, 1 3 1 5:2 | 6:2 5 4 3:2 1:2 | 7:3 5 4:2 2:2 | 4:6 -:2",
        arp: "up",
        pad: "offbeat",
        bass: "sync",
        drums: "electro",
        energy: 0.65,
      },
      B: {
        bars: 8,
        chords: "4 5 6 3 4 5 7 7",
        lead: "1':4 6:2 4:2 | 7:4 5:2 2':2 | 3':4 1':2 6:2 | 5:6 -:2 | 4:4 6:2 1':2 | 2':4 1':2 7:2 | 5:3 7:3 2':2 | 2':8",
        counter: "-:4 4, 6, 1 4, | -:4 5, 7, 2 5, | -:4 6, 1 3 6, | -:4 3, 5, 7, 3,",
        arp: "cascade",
        pad: "hold",
        bass: "octave",
        drums: "four",
        energy: 0.78,
      },
      C: {
        bars: 8,
        chords: "6 7 1 1",
        lead: "3:8 | 2:4 7,:4 | 1:8 | _:8",
        arp: "sparse",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.28,
      },
      D: {
        bars: 8,
        chords: "1 1 6 6 3 3 7 7",
        lead: "1:0.5 3:0.5 5:0.5 1':0.5 5:0.5 3:0.5 1:0.5 3:0.5 5:2 1':2 | 1':3 7 5:4 | 6,:0.5 1:0.5 3:0.5 6:0.5 3:0.5 1:0.5 6,:0.5 1:0.5 3:2 6:2 | 6:3 5 3:4 | 3:0.5 5:0.5 1':0.5 3':0.5 1':0.5 5:0.5 3:0.5 5:0.5 1':2 3':2 | 3':3 2' 5:4 | 2:0.5 4:0.5 7:0.5 2':0.5 7:0.5 4:0.5 2:0.5 4:0.5 7:2 2':2 | 2':4 7:2 5:2",
        arp: "pulse",
        pad: "stab",
        bass: "arp",
        drums: "break",
        energy: 0.85,
        fill: true,
      },
      outro: {
        bars: 4,
        chords: "1 6 7 1",
        arp: "up",
        pad: "swell",
        bass: "hold",
        drums: "none",
        energy: 0.2,
      },
    },
    form: [
      "intro",
      "A",
      "A",
      "B",
      "B",
      "A",
      "C",
      "D",
      "D",
      "A",
      "A",
      "B",
      "B",
      "C",
      "D",
      "A",
      "A",
      "outro",
    ],
  },
];
