// _unOS Virtual Filesystem
// In-memory Unix-like filesystem for the terminal interface

export interface VirtualNode {
  name: string
  type: 'file' | 'dir' | 'symlink'
  content?: string
  children?: Map<string, VirtualNode>
  permissions: number // octal, e.g. 0o755
  owner: string
  group: string
  modified: number
  size: number
  target?: string // symlink target
}

export class VirtualFS {
  root: VirtualNode
  private _cwd: string = '/home/operator'
  private _previousCwd: string = '/home/operator'

  constructor() {
    this.root = this.buildDefaultTree()
  }

  get cwd(): string {
    return this._cwd
  }

  private mknode(
    name: string,
    type: 'file' | 'dir' | 'symlink',
    opts: {
      content?: string
      permissions?: number
      owner?: string
      group?: string
      target?: string
    } = {}
  ): VirtualNode {
    const now = Date.now()
    const node: VirtualNode = {
      name,
      type,
      permissions: opts.permissions ?? (type === 'dir' ? 0o755 : 0o644),
      owner: opts.owner ?? 'root',
      group: opts.group ?? 'root',
      modified: now,
      size: opts.content?.length ?? 0,
    }
    if (type === 'dir') {
      node.children = new Map()
    }
    if (opts.content !== undefined) {
      node.content = opts.content
    }
    if (opts.target) {
      node.target = opts.target
    }
    return node
  }

  private addChild(parent: VirtualNode, child: VirtualNode): VirtualNode {
    parent.children!.set(child.name, child)
    return child
  }

  private buildDefaultTree(): VirtualNode {
    const root = this.mknode('/', 'dir', { permissions: 0o755 })

    // /bin
    const bin = this.addChild(root, this.mknode('bin', 'dir'))
    for (const cmd of ['ls', 'cd', 'cat', 'mkdir', 'touch', 'rm', 'chmod', 'chown', 'pwd', 'echo', 'tree', 'clear', 'su', 'sudo', 'passwd', 'id', 'groups', 'whoami', 'useradd']) {
      this.addChild(bin, this.mknode(cmd, 'file', { permissions: 0o755, content: `#!/bin/sh\n# ${cmd} - _unOS builtin` }))
    }

    // /etc
    const etc = this.addChild(root, this.mknode('etc', 'dir'))
    const etcUnos = this.addChild(etc, this.mknode('_unOS', 'dir'))
    this.addChild(etcUnos, this.mknode('lab.conf', 'file', {
      content: [
        '# _unOS Laboratory Configuration',
        '# Generated by _unLAB installer v2.1.0',
        '',
        '[general]',
        'lab_name = _unLAB',
        'lab_id = UL-0001',
        'version = 2.1.0',
        'mode = DEVELOPER',
        '',
        '[crystals]',
        'max_crystals = 100',
        'slices_per_crystal = 30',
        'auto_stabilize = true',
        '',
        '[economy]',
        'token = _unSC',
        'mint_cost = 50',
        'network = solana-devnet',
        '',
        '[security]',
        'level = MAXIMUM',
        'encryption = AES-256',
        'session_timeout = 3600',
      ].join('\n'),
    }))
    this.addChild(etcUnos, this.mknode('blockchain.conf', 'file', {
      content: [
        '# Blockchain Configuration',
        '',
        '[network]',
        'chain = solana',
        'cluster = devnet',
        'rpc_url = https://api.devnet.solana.com',
        'ws_url = wss://api.devnet.solana.com',
        '',
        '[volatility]',
        'tracking = enabled',
        'sample_interval = 5000',
        'tier_thresholds = 500,1500,3000,4500',
        '',
        '[tokens]',
        'program_id = UnSC...redacted',
        'mint_authority = system',
      ].join('\n'),
    }))

    const etcDevices = this.addChild(etcUnos, this.mknode('devices', 'dir'))
    this.addChild(etcDevices, this.mknode('btk.conf', 'file', {
      content: [
        '# BTK-001 Configuration',
        'device.id=BTK-001',
        'device.name=Basic Toolkit',
        'device.tier=1',
        'device.maker=HNDX',
        'power.full=0.5',
        'power.idle=0.3',
        'power.standby=0.05',
        'power.category=light',
        'power.priority=2',
        'tools.count=4',
        'tools.list=PROBE,CLAMP,LASER,DRILL',
        'calibration.auto=true',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('rmg.conf', 'file', {
      content: [
        '# RMG-001 Configuration',
        'device.id=RMG-001',
        'device.name=Resource Magnet',
        'device.tier=1',
        'device.maker=TESLA',
        'power.full=5.0',
        'power.idle=3.0',
        'power.standby=0.2',
        'power.category=medium',
        'power.priority=3',
        'field.strength=45',
        'field.auto_calibrate=true',
        'coils.count=3',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('msc.conf', 'file', {
      content: [
        '# MSC-001 Configuration',
        'device.id=MSC-001',
        'device.name=Material Scanner',
        'device.tier=1',
        'device.maker=SCNR',
        'power.full=2.0',
        'power.idle=1.0',
        'power.standby=0.1',
        'power.category=light',
        'power.priority=2',
        'scan.sweep_speed=50',
        'scan.auto_calibrate=true',
        'emitter.power=75',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('tmp.conf', 'file', {
      content: [
        '# TMP-001 Configuration',
        'device.id=TMP-001',
        'device.name=Temperature Monitor',
        'device.tier=1',
        'device.maker=INTL',
        'power.full=1.2',
        'power.idle=0.8',
        'power.standby=0.1',
        'power.category=light',
        'power.priority=1',
        'sensor.count=3',
        'sensor.interval=500',
        'threshold.warning=60',
        'threshold.critical=75',
        'calibrate.auto=true',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('net.conf', 'file', {
      content: [
        '# NET-001 Configuration',
        'device.id=NET-001',
        'device.name=Network Monitor',
        'device.tier=2',
        'device.maker=CSCO',
        'power.full=1.5',
        'power.idle=0.8',
        'power.standby=0.1',
        'power.category=light',
        'power.priority=2',
        'nic.auto_detect=true',
        'dhcp.enabled=true',
        'monitor.interval=200',
        'latency.threshold=100',
        'packet.inspect=true',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('clk.conf', 'file', {
      content: [
        '# CLK-001 Configuration',
        'device.id=CLK-001',
        'device.name=Lab Clock',
        'device.version=2.4.0',
        'device.maker=SIKO',
        'power.full=0.5',
        'power.idle=0.3',
        'power.standby=0.02',
        'power.category=light',
        'power.priority=1',
        'crystal.freq=32768',
        'ntp.server=time.unos.local',
        'ntp.interval=3600',
        'drift.compensation=auto',
        'display.default=local',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('cpu.conf', 'file', {
      content: [
        '# CPU-001 Configuration',
        'device.id=CPU-001',
        'device.name=CPU Monitor',
        'device.version=3.2.1',
        'device.maker=AMTD',
        'power.full=0.8',
        'power.idle=0.5',
        'power.standby=0.05',
        'power.category=light',
        'power.priority=1',
        'cores=8',
        'frequency.base=4.2',
        'frequency.boost=5.1',
        'thermal.limit=95',
        'cache.l1=64',
        'cache.l2=512',
        'monitor.interval=200',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('mem.conf', 'file', {
      content: [
        '# MEM-001 Configuration',
        'device.id=MEM-001',
        'device.name=Memory Monitor',
        'device.version=3.1.0',
        'device.maker=CRSR',
        'power.full=0.6',
        'power.idle=0.4',
        'power.standby=0.05',
        'power.category=light',
        'power.priority=1',
        'dimm.slots=4',
        'dimm.type=DDR5',
        'dimm.speed=5600',
        'total.capacity=16',
        'display.default=usage',
        'monitor.interval=500',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('and.conf', 'file', {
      content: [
        '# AND-001 Configuration',
        'device.id=AND-001',
        'device.name=Anomaly Detector',
        'device.version=2.3.0',
        'device.maker=HALO',
        'power.full=4',
        'power.idle=2',
        'power.standby=0.1',
        'power.category=medium',
        'power.priority=2',
        'sensor.type=waveform',
        'sensor.range=0-100',
        'scan.interval=100',
        'halo.link=enabled',
        'display.default=waveform',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('qcp.conf', 'file', {
      content: [
        '# QCP-001 Configuration',
        'device.id=QCP-001',
        'device.name=Quantum Compass',
        'device.version=1.5.0',
        'device.maker=QNTM',
        'power.full=2.5',
        'power.idle=0.8',
        'power.standby=0.2',
        'power.category=light',
        'power.priority=3',
        'gyro.sensitivity=high',
        'magnetometer.range=360',
        'quantum.link=entangled',
        'needle.stabilize=true',
        'display.default=compass',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('dim.conf', 'file', {
      content: [
        '# DIM-001 Configuration',
        'device.id=DIM-001',
        'device.name=Dimension Monitor',
        'device.tier=2',
        'device.maker=DIME',
        'power.full=1.5',
        'power.idle=0.8',
        'power.standby=0.1',
        'power.category=light',
        'power.priority=2',
        'dimension.target=3.14',
        'stability.threshold=80',
        'rift.sensitivity=0.05',
        'halo.alert_distance=20',
        'scan.interval=300',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('pwb.conf', 'file', {
      content: [
        '# PWB-001 Configuration',
        'device.id=PWB-001',
        'device.name=Portable Workbench',
        'device.tier=1',
        'device.maker=FABX',
        'power.full=3.0',
        'power.idle=0.8',
        'power.standby=0.15',
        'power.category=light',
        'power.priority=2',
        'slots.count=3',
        'calibration.auto=true',
      ].join('\n'),
    }))
    this.addChild(etcDevices, this.mknode('tlp.conf', 'file', {
      content: [
        '# TLP-001 Teleport Pad Configuration',
        '# WARP Industries — Quantum Transport Module',
        'device_id=TLP-001',
        'firmware=2.2.0',
        'serial=WARP-TLP-2025-0810',
        'power_full=35',
        'power_idle=3',
        'power_standby=0.5',
        'category=heavy',
        'priority=4',
        'charge_default=65',
        'destination_default=LAB-Ω',
        'mode_default=standard',
        'modes=standard,precision,express,stealth,cargo,emergency',
        'compatible=UEC-001,MFR-001,DIM-001,QSM-001',
      ].join('\n'),
    }))

    this.addChild(etcDevices, this.mknode('lct.conf', 'file', {
      content: [
        '# LCT-001 Precision Laser Configuration',
        '# OPTX Industries — High-Precision Laser Module',
        'device_id=LCT-001',
        'firmware=2.1.0',
        'serial=OPTX-LCT-2025-0720',
        'power_full=25',
        'power_idle=4',
        'power_standby=0.5',
        'category=heavy',
        'priority=3',
        'laser_power_default=450',
        'precision_default=0.01',
        'mode_default=cutting',
        'modes=cutting,engraving,welding,marking,drilling,scanning',
        'compatible=UEC-001,MFR-001,DIM-001,QSM-001',
      ].join('\n'),
    }))

    this.addChild(etcDevices, this.mknode('p3d.conf', 'file', {
      content: [
        '# P3D-001 3D Fabricator Configuration',
        '# PRSA Industries — Additive Manufacturing Module',
        'device_id=P3D-001',
        'firmware=3.2.1',
        'serial=PRSA-P3D-2025-0615',
        'power_full=18',
        'power_idle=3',
        'power_standby=0.5',
        'category=heavy',
        'priority=3',
        'progress_default=67',
        'layer_default=234',
        'bedtemp_default=60',
        'mode_default=plastic',
        'modes=plastic,metal,crystal,composite,nano,prototype',
        'compatible=PWB-001,MSC-001,LCT-001,BTK-001',
      ].join('\n'),
    }))

    const etcScrewButtons = this.addChild(etcUnos, this.mknode('screwbuttons', 'dir'))
    for (const [id, conf] of [
      ['sb01', 'SB-01|NODE-SYNC|top-left|enabled'],
      ['sb02', 'SB-02|POOL-LINK|top-right|enabled'],
      ['sb03', 'SB-03|MESH-CAST|bottom-left|enabled'],
      ['sb04', 'SB-04|QUANTUM-BRIDGE|bottom-right|enabled'],
    ]) {
      this.addChild(etcScrewButtons, this.mknode(`${id}.conf`, 'file', {
        content: `# Screw Button Configuration\n# Auto-generated by _unOS\n${conf}\n`,
      }))
    }

    this.addChild(etc, this.mknode('passwd', 'file', {
      permissions: 0o644,
      content: [
        'root:x:0:0:root:/root:/bin/sh',
        'adm:x:1000:1000:Lab Administrator:/home/adm:/bin/sh',
        'operator:x:1001:1001:Lab Operator:/home/operator:/bin/sh',
      ].join('\n'),
    }))

    this.addChild(etc, this.mknode('shadow', 'file', {
      permissions: 0o600,
      content: [
        'root:$6$rounds=656000$locked::0:99999:7:::',
        'adm:$6$rounds=656000$hashed_placeholder::0:99999:7:::',
        'operator:$6$rounds=656000$hashed_placeholder::0:99999:7:::',
      ].join('\n'),
    }))

    this.addChild(etc, this.mknode('group', 'file', {
      content: [
        'root:x:0:root',
        'wheel:x:10:adm',
        'sudo:x:27:adm',
        'adm:x:1000:adm',
        'operator:x:1001:operator',
        'games:x:1002:operator',
      ].join('\n'),
    }))

    this.addChild(etc, this.mknode('hostname', 'file', {
      content: '_unLAB',
    }))

    this.addChild(etc, this.mknode('motd', 'file', {
      content: [
        '',
        '  ██╗   ██╗███╗   ██╗ ██████╗ ███████╗',
        '  ██║   ██║████╗  ██║██╔═══██╗██╔════╝',
        '  ██║   ██║██╔██╗ ██║██║   ██║███████╗',
        '  ██║   ██║██║╚██╗██║██║   ██║╚════██║',
        '  ╚██████╔╝██║ ╚████║╚██████╔╝███████║',
        '   ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚══════╝',
        '',
        '  Welcome to _unOS v2.1.0 (Quantum Kernel 6.1.0-_unSC)',
        '  Last login: session start',
        '',
      ].join('\n'),
    }))

    // /home
    const home = this.addChild(root, this.mknode('home', 'dir'))

    // /home/operator
    const opHome = this.addChild(home, this.mknode('operator', 'dir', { owner: 'operator', group: 'operator', permissions: 0o750 }))
    this.addChild(opHome, this.mknode('.bashrc', 'file', {
      owner: 'operator', group: 'operator',
      content: '# _unOS operator shell config\nexport PS1="\\u@_unLAB:\\w$ "\nexport PATH=/bin:/usr/bin\n',
    }))
    this.addChild(opHome, this.mknode('.profile', 'file', {
      owner: 'operator', group: 'operator',
      content: '# operator profile\necho "Welcome, operator."\n',
    }))
    // .local/docs - device documentation
    const opLocal = this.addChild(opHome, this.mknode('.local', 'dir', { owner: 'operator', group: 'operator' }))
    const opLocalDocs = this.addChild(opLocal, this.mknode('docs', 'dir', { owner: 'operator', group: 'operator' }))
    this.addChild(opLocalDocs, this.mknode('emc001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        '═══════════════════════════════════════════════════════════',
        '  EMC-001 :: EXOTIC MATTER CONTAINMENT',
        '  Device Specification v4.0',
        '═══════════════════════════════════════════════════════════',
        '',
        'OVERVIEW',
        '  High-energy containment field for exotic matter particles.',
        '  Magnetic confinement system (CERN-class) with real-time',
        '  monitoring of particle count, stability, and field strength.',
        '',
        'SPECIFICATIONS',
        '  Device ID:     EMC-001',
        '  Firmware:      v4.0.1 (build 2026.01.15)',
        '  Checksum:      E8X4M2C7',
        '  Particles:     42 units (max capacity)',
        '  Field Type:    Magnetic confinement',
        '  Temperature:   800-1200°K (operational)',
        '',
        'POWER',
        '  Full:          40 E/s',
        '  Idle:          18 E/s',
        '  Standby:       2 E/s',
        '  Scan/Test:     55 E/s',
        '  Category:      Heavy',
        '  Priority:      P1 (Critical)',
        '',
        'FEATURES',
        '  - containment-field : Magnetic confinement barrier',
        '  - particle-tracking : Real-time particle position monitor',
        '  - stability-calc    : Containment stability percentage',
        '  - matter-compress   : Exotic matter compression system',
        '  - field-harmonics   : Field resonance harmonics',
        '',
        'COMMANDS',
        '  emc status           Show containment status',
        '  emc power [on|off]   Power on/off containment field',
        '  emc firmware         View firmware info',
        '  emc firmware update  Check for firmware updates',
        '  emc test             Run containment diagnostics',
        '  emc reset            Reboot containment system',
        '  emc info             Show this documentation',
        '',
        'BOOT SEQUENCE',
        '  1. field       - Generate containment field',
        '  2. containment - Establish magnetic boundary',
        '  3. particles   - Load exotic matter particles',
        '  4. stabilize   - Stabilize field harmonics',
        '  5. ready       - Containment online',
        '',
        'SHUTDOWN SEQUENCE',
        '  1. decontain   - Release field pressure',
        '  2. collapse    - Collapse containment barrier',
        '  3. cooldown    - Thermal stabilization',
        '',
        'TROUBLESHOOTING',
        '  - Low stability: check field strength and temperature',
        '  - Field collapse: immediate reboot with emc reset',
        '  - If containment offline, run: emc power on',
        '  - Run emc test to verify all containment systems',
        '  - High temperature (>1100°K): monitor closely',
        '',
        'COMPATIBLE DEVICES',
        '  MFR-001  Microfusion Reactor (power source)',
        '  QAN-001  Quantum Analyzer (quantum operations)',
        '  DGN-001  Diagnostics Module (monitoring)',
        '',
        '═══════════════════════════════════════════════════════════',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('qsm001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        '═══════════════════════════════════════════════════════════',
        '  QSM-001 :: QUANTUM STATE MONITOR',
        '  Device Specification v1.2',
        '═══════════════════════════════════════════════════════════',
        '',
        'OVERVIEW',
        '  127-qubit quantum coherence monitor with real-time wave',
        '  function visualization. Tracks entanglement state,',
        '  coherence percentage, error rates, and cryogenic temp.',
        '',
        'SPECIFICATIONS',
        '  Device ID:     QSM-001',
        '  Firmware:      v1.2.0 (build 2026.01.20)',
        '  Checksum:      Q7S4M1N9',
        '  Qubit Array:   127 qubits (IBM Eagle topology)',
        '  Coherence:     T2 ~ 120μs',
        '  Error Correct: Surface code, distance 3',
        '  Cryogenics:    15°K dilution refrigerator',
        '',
        'POWER',
        '  Full:          12 E/s',
        '  Idle:          7 E/s',
        '  Standby:       1 E/s',
        '  Scan/Test:     18 E/s',
        '  Category:      Medium',
        '  Priority:      P2',
        '',
        'FEATURES',
        '  - qubit-array        : 127-qubit register',
        '  - coherence-tracking : Real-time T2 measurement',
        '  - entanglement-verify: Bell state fidelity check',
        '  - error-correction   : Surface code decoder',
        '  - wave-function      : Animated |ψ⟩ display',
        '',
        'COMMANDS',
        '  qsm status           Show quantum state',
        '  qsm power [on|off]   Power on/off',
        '  qsm firmware         View firmware info',
        '  qsm firmware update  Check for updates',
        '  qsm test             Run quantum diagnostics',
        '  qsm reset            Reboot quantum monitor',
        '  qsm info             Show this documentation',
        '',
        'BOOT SEQUENCE',
        '  1. cooling    - Cool qubit array to 15°K',
        '  2. calibrate  - Calibrate qubit frequencies',
        '  3. entangle   - Establish Bell pairs',
        '  4. stabilize  - Error correction init',
        '  5. ready      - Monitor online',
        '',
        'SHUTDOWN SEQUENCE',
        '  1. collapse   - Collapse quantum states',
        '  2. decohere   - Allow decoherence',
        '  3. cooldown   - Thermal stabilization',
        '',
        'TROUBLESHOOTING',
        '  - Low coherence: check cryogenic system temperature',
        '  - No entanglement: run qsm test to verify Bell states',
        '  - High error rate: reboot with qsm reset',
        '  - If display frozen: run qsm power off, then qsm power on',
        '',
        'COMPATIBLE DEVICES',
        '  QAN-001  Quantum Analyzer (quantum operations)',
        '  SCA-001  Supercomputer Array (classical control)',
        '  AIC-001  AI Assistant Core (error optimization)',
        '',
        '═══════════════════════════════════════════════════════════',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('qua001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        '═══════════════════════════════════════════════════════════',
        '  QUA-001 :: QUANTUM ANALYZER',
        '  Device Specification v3.7',
        '═══════════════════════════════════════════════════════════',
        '',
        'OVERVIEW',
        '  Universal problem solver with 6 analysis modes,',
        '  neural network processing, waveform generation,',
        '  and deep scan capability.',
        '',
        'SPECIFICATIONS',
        '  Device ID:     QUA-001 (QAN-001)',
        '  Firmware:      v3.7.2 (build 2026.01.29)',
        '  Checksum:      Q7A3N5X8',
        '  Manufacturer:  QNTX Corporation',
        '  Analysis Modes: ANOMALY, RESOURCE, DECRYPT,',
        '                  DIAGNOSE, SIMULATE, SCAN',
        '',
        'POWER',
        '  Full:          25 E/s',
        '  Idle:          10 E/s',
        '  Standby:       2 E/s',
        '  Analysis:      35 E/s',
        '  Category:      Heavy',
        '  Priority:      P2',
        '',
        'FEATURES',
        '  - quantum-core     : Quantum processing engine',
        '  - neural-network   : Pattern recognition & analysis',
        '  - multi-mode       : 6 analysis mode support',
        '  - waveform-gen     : Real-time waveform display',
        '  - deep-scan        : Sub-surface object detection',
        '',
        'COMMANDS',
        '  qua status              Show analyzer status',
        '  qua power [on|off]      Power on/standby',
        '  qua firmware            View firmware info',
        '  qua firmware update     Check for firmware updates',
        '  qua test                Run diagnostics',
        '  qua reset               Reboot analyzer',
        '  qua mode <MODE>         Set analysis mode',
        '  qua sensitivity <0-100> Set sensitivity knob',
        '  qua depth <0-100>       Set depth knob',
        '  qua frequency <0-100>   Set frequency knob',
        '  qua info                Show this documentation',
        '',
        'BOOT SEQUENCE',
        '  1. core       - Initialize quantum core',
        '  2. sensors    - Calibrate sensor array',
        '  3. neural     - Load neural network',
        '  4. calibrate  - System calibration',
        '  5. ready      - Analyzer online',
        '',
        'SHUTDOWN SEQUENCE',
        '  1. save       - Save analysis state',
        '  2. release    - Release resources',
        '  3. offline    - Power down',
        '',
        'ANALYSIS MODES',
        '  ANOMALY   - Detect & classify dimensional anomalies',
        '  RESOURCE  - Optimize resource allocation & yield',
        '  DECRYPT   - Decode encrypted signals & data',
        '  DIAGNOSE  - System health & fault detection',
        '  SIMULATE  - Run predictive simulations',
        '  SCAN      - Deep scan for hidden objects',
        '',
        'COMPATIBLE DEVICES',
        '  EMC-001  Exotic Matter Containment (anomaly source)',
        '  QSM-001  Quantum State Monitor (quantum feed)',
        '  SCA-001  Supercomputer Array (compute offload)',
        '',
        '═══════════════════════════════════════════════════════════',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('rmg001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'RMG-001 RESOURCE MAGNET',
        '===========================',
        'Type:     Passive Resource Attractor',
        'Tier:     1',
        'Maker:    TESLA (Tesla Coil Systems)',
        'Firmware: v1.2.0',
        '',
        'OVERVIEW',
        '--------',
        'Electromagnetic resource attractor using concentric',
        'field rings. Variable strength control via integrated',
        'coil system. Auto-calibration for optimal flux density.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     5.0 E/s',
        'Idle:     3.0 E/s',
        'Standby:  0.2 E/s',
        'Category: Medium',
        'Priority: 3',
        '',
        'FEATURES',
        '--------',
        '- Variable strength coil control (0-100%)',
        '- Concentric field ring visualization',
        '- Flux density monitoring',
        '- Auto-calibration system',
        '- Field stability feedback',
        '',
        'COMMANDS',
        '--------',
        'rmg status     - Device status',
        'rmg firmware   - Firmware information',
        'rmg test       - Run diagnostics',
        'rmg config     - View configuration',
        'rmg field      - Field status',
        'rmg strength N - Set strength (0-100)',
        'rmg reboot     - Reboot device',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('unmc.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'unMC — MIDNIGHT COMMANDER FOR _unOS',
        '====================================',
        'Version:  2.0.0 (interactive)',
        'Based on: GNU Midnight Commander',
        'Source:   github.com/MidnightCommander/mc',
        '',
        'OVERVIEW',
        '--------',
        'Interactive dual-pane file manager for _unOS.',
        'Full keyboard-driven interface with file',
        'browsing, editing, copying, moving, and more.',
        '',
        'COMMANDS',
        '--------',
        'unmc              Launch interactive file manager',
        'unmc help         Show keyboard shortcuts',
        'unmc info         Version information',
        'unmcedit <file>   Open file directly in editor',
        '',
        'KEYBOARD (inside MC)',
        '--------------------',
        '↑/↓         Navigate files',
        'Tab         Switch between panes',
        'Enter       Open directory / view file',
        'Backspace   Go to parent directory',
        'F3          View file (read-only)',
        'F4          Edit file',
        'F5          Copy to other pane',
        'F6          Move/rename',
        'F7          Create directory',
        'F8          Delete',
        'Esc/F10     Quit MC',
        '',
        'EDITOR KEYS (F4 / unmcedit)',
        '---------------------------',
        'Arrow keys  Move cursor',
        'Home/End    Start/end of line',
        'PgUp/PgDn   Scroll page',
        'Enter       New line',
        'Backspace   Delete char before cursor',
        'Delete      Delete char at cursor',
        'Tab         Insert 2 spaces',
        'Ctrl+S/F2   Save file',
        'Esc/F10     Quit editor (prompts to save)',
        '',
        'ALIASES',
        '-------',
        'mc        Shorthand for unmc',
        'mcedit    Shorthand for unmcedit',
        '',
        'NOTES',
        '-----',
        'Panel state (left/right paths) persists across',
        'sessions via local storage.',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('msc001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'MSC-001 MATERIAL SCANNER',
        '===========================',
        'Type:     Handheld Resource Detector',
        'Tier:     1',
        'Maker:    SCNR (Scanner Technologies)',
        'Firmware: v1.3.0',
        '',
        'OVERVIEW',
        '--------',
        'Handheld scanning device for resource detection.',
        'Identifies nearby resource nodes and small anomalies.',
        'Helps locate Abstractum deposits and flags minor',
        'anomaly signals via sweep-scan emitter/receiver pair.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     2.0 E/s',
        'Idle:     1.0 E/s',
        'Standby:  0.1 E/s',
        'Category: Light',
        'Priority: 2',
        '',
        'FEATURES',
        '--------',
        '- Material detection sweep scanning',
        '- Anomaly signal flagging',
        '- Auto-calibration system',
        '- Real-time scan line visualization',
        '',
        'COMMANDS',
        '--------',
        'msc status     - Device status',
        'msc firmware   - Firmware information',
        'msc test       - Run diagnostics',
        'msc config     - View configuration',
        'msc reboot     - Reboot device',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('net001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'NET-001 NETWORK MONITOR',
        '===========================',
        'Type:     Network Throughput Monitor',
        'Tier:     2',
        'Maker:    CSCO (Cisco Technologies)',
        'Firmware: v2.1.0',
        '',
        'OVERVIEW',
        '--------',
        'Real-time network throughput and connectivity',
        'monitor. Tracks bandwidth utilization, latency,',
        'packet integrity, and connection security.',
        'Animated bandwidth bar visualization with',
        'NIC detection and DHCP auto-configuration.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     1.5 E/s',
        'Idle:     0.8 E/s',
        'Standby:  0.1 E/s',
        'Category: Light',
        'Priority: 2',
        '',
        'FIRMWARE FEATURES',
        '-----------------',
        '- nic-detect        NIC auto-detection',
        '- dhcp-client       DHCP address acquisition',
        '- throughput-monitor Real-time bandwidth tracking',
        '- latency-track     Latency measurement',
        '- packet-inspect    Packet integrity checking',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'POST → NIC detect → DHCP request → Handshake',
        '→ Sync routes → CONNECTED',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Latency test → Bandwidth test → Packet integrity',
        '→ Security check → Complete',
        '',
        'COMMANDS',
        '--------',
        'net status     - Device status',
        'net firmware   - Firmware information',
        'net test       - Run diagnostics',
        'net config     - View configuration',
        'net reboot     - Reboot device',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('tmp001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'TMP-001 TEMPERATURE MONITOR',
        '===========================',
        'Type:     Thermal Monitoring System',
        'Tier:     1',
        'Maker:    INTL (Intel Technologies)',
        'Firmware: v1.0.0',
        '',
        'OVERVIEW',
        '--------',
        'Multi-sensor thermal monitoring system for lab',
        'equipment. Tracks CPU, GPU, and ambient temperatures.',
        'Provides threshold alerts and cooling system',
        'integration with color-coded gradient display.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     1.2 E/s',
        'Idle:     0.8 E/s',
        'Standby:  0.1 E/s',
        'Category: Light',
        'Priority: 1',
        '',
        'FIRMWARE FEATURES',
        '-----------------',
        '- thermal-probe     Multi-point thermal probing',
        '- multi-sensor      Multiple sensor support',
        '- threshold-alert   Configurable temp alerts',
        '- cooling-monitor   Cooling system integration',
        '- auto-calibrate    Automatic sensor calibration',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'POST → Sensor init → Calibration → Reading',
        '→ NOMINAL',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Sensor test → Calibration test → Threshold verify',
        '→ Cooling check → Complete',
        '',
        'COMMANDS',
        '--------',
        'tmp status     - Device status',
        'tmp firmware   - Firmware information',
        'tmp test       - Run diagnostics',
        'tmp config     - View configuration',
        'tmp reboot     - Reboot device',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('clk001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'CLK-001 LAB CLOCK',
        '=================',
        'Type:     Time Display System',
        'Tier:     1',
        'Maker:    SIKO',
        'Firmware: v2.4.0',
        '',
        'OVERVIEW',
        '--------',
        'Multi-mode time display system with 6 modes.',
        'Crystal-accurate RTC with NTP synchronization',
        'and automatic drift compensation.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     0.5 E/s',
        'Idle:     0.3 E/s',
        'Standby:  0.02 E/s',
        'Category: Light',
        'Priority: 1',
        '',
        'DISPLAY MODES',
        '-------------',
        'LOCAL      Local time (HH:MM:SS)',
        'UTC        Coordinated Universal Time',
        'DATE       Current date (MM/DD/YY)',
        'UPTIME     Session uptime counter',
        'COUNTDOWN  Configurable countdown timer',
        'STOPWATCH  Start/stop/reset stopwatch',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'Crystal init → RTC sync → NTP query',
        '→ Calibrate → Drift comp → SYNCED',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Test phases: crystal, sync, drift, accuracy',
        '',
        'COMMANDS',
        '--------',
        'clk status     Show device status',
        'clk firmware   Show firmware info',
        'clk test       Run diagnostics',
        'clk config     View configuration',
        'clk mode       Cycle display mode',
        'clk mode <name> Set specific mode',
        'clk reboot     Reboot device',
        '',
        'COMPATIBLE DEVICES',
        '------------------',
        'DGN-001, SCA-001, all monitoring devices',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('cpu001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'CPU-001 CPU MONITOR',
        '===================',
        'Type:     Processor Monitor',
        'Tier:     1',
        'Maker:    AMTD (Advanced Micro-Thermal Dynamics)',
        'Firmware: v3.2.1',
        '',
        'OVERVIEW',
        '--------',
        'Multi-core processor utilization monitor.',
        'Tracks per-core loads, frequency scaling,',
        'thermal limits, and cache integrity.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     0.8 E/s',
        'Idle:     0.5 E/s',
        'Standby:  0.05 E/s',
        'Category: Light',
        'Priority: 1',
        '',
        'FEATURES',
        '--------',
        '- Multi-core load monitoring (up to 16 cores)',
        '- Frequency scaling with boost detection',
        '- Thermal link to TMP-001 / VNT-001',
        '- L1/L2 cache analysis',
        '- Stress test with full core saturation',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'POST → Detect cores → Init cache → Freq scale',
        '→ Calibrate → READY',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Test phases: cores, cache, frequency, thermal, stress',
        'Stress test runs all cores at ~95% for 600ms.',
        '',
        'COMMANDS',
        '--------',
        'cpu status     Show device status',
        'cpu firmware   Show firmware info',
        'cpu test       Run diagnostics',
        'cpu config     View configuration',
        'cpu reboot     Reboot device',
        '',
        'COMPATIBLE DEVICES',
        '------------------',
        'TMP-001, VNT-001, SCA-001, MFR-001',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('mem001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'MEM-001 MEMORY MONITOR',
        '======================',
        'Type:     RAM/Memory Display',
        'Tier:     1',
        'Maker:    CRSR (Corsair Systems Research)',
        'Firmware: v3.1.0',
        '',
        'OVERVIEW',
        '--------',
        'Multi-mode RAM/memory display with 6 modes.',
        'Monitors DDR5 DIMMs, heap/stack allocation,',
        'cache levels, swap usage, and top processes.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     0.6 E/s',
        'Idle:     0.4 E/s',
        'Standby:  0.05 E/s',
        'Category: Light',
        'Priority: 1',
        '',
        'DISPLAY MODES',
        '-------------',
        'USAGE       Main RAM usage bar',
        'HEAP        Heap/Stack allocation',
        'CACHE       L1/L2/L3 cache levels',
        'SWAP        Swap partition usage',
        'PROCESSES   Top 5 memory consumers',
        'ALLOCATION  Kernel/User/Buffer split',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'DIMM detect → SPD read → Timing config',
        '→ Memory test → Mapping → READY',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Test phases: modules, timing, integrity,',
        'bandwidth, stress. Stress fills to 95%.',
        '',
        'COMMANDS',
        '--------',
        'mem status     Show device status',
        'mem firmware   Show firmware info',
        'mem test       Run diagnostics',
        'mem config     View configuration',
        'mem mode       Cycle display mode',
        'mem mode <name> Set specific mode',
        'mem reboot     Reboot device',
        '',
        'COMPATIBLE DEVICES',
        '------------------',
        'CPU-001, SCA-001, DGN-001',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('and001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'AND-001 ANOMALY DETECTOR',
        '========================',
        'Type:     Anomaly Scanner / Signal Analyzer',
        'Tier:     2',
        'Maker:    HALO (Halo Plane Technologies)',
        'Firmware: v2.3.0',
        '',
        'OVERVIEW',
        '--------',
        'Waveform-based anomaly detection system.',
        'Scans dimensional rifts and quantum anomalies',
        'in real-time using multi-mode signal analysis.',
        'Features HALO link for cross-plane data sharing.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     4 E/s',
        'Idle:     2 E/s',
        'Standby:  0.1 E/s',
        'Category: Medium',
        'Priority: 2',
        '',
        'DISPLAY MODES',
        '-------------',
        'WAVEFORM    Real-time signal waveform',
        'SPECTRUM    Frequency spectrum analysis',
        'HEATMAP     2D anomaly intensity map',
        'TIMELINE    Historical anomaly events',
        'FREQUENCY   Frequency domain view',
        'RADAR       Directional radar sweep',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'Sensor init → Calibration → Freq sweep',
        '→ Scanning → Analysis → SCANNING',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Test phases: sensors, calibrate, sweep,',
        'analyze, verify. Sweep boosts signal to 95%.',
        '',
        'COMMANDS',
        '--------',
        'and status     Show device status',
        'and firmware   Show firmware info',
        'and test       Run diagnostics',
        'and config     View configuration',
        'and mode       Cycle display mode',
        'and mode <name> Set specific mode',
        'and signal <n> Set signal strength',
        'and reboot     Reboot device',
        '',
        'COMPATIBLE DEVICES',
        '------------------',
        'QSM-001, DIM-001, EMC-001, QAN-001',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('qcp001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'QCP-001 QUANTUM COMPASS',
        '=======================',
        'Type:     Anomaly Direction Finder',
        'Tier:     2',
        'Maker:    QNTM (Quantum Navigation Tech.)',
        'Firmware: v1.5.0',
        '',
        'OVERVIEW',
        '--------',
        'Quantum-entangled anomaly direction finder.',
        'Tracks anomaly direction and distance using',
        'gyroscope, magnetometer, and quantum link.',
        'Needle stabilization for accurate readings.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     2.5 E/s',
        'Idle:     0.8 E/s',
        'Standby:  0.2 E/s',
        'Category: Light',
        'Priority: 3',
        '',
        'DISPLAY MODES',
        '-------------',
        'COMPASS       Classic needle compass',
        'RADAR         Radar sweep display',
        'HEATMAP       Anomaly intensity map',
        'TRAJECTORY    Predicted anomaly path',
        'TRIANGULATE   Multi-point triangulation',
        'HISTORY       Historical bearing log',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'Gyro init → Magnetometer → Quantum link',
        '→ Calibrate → Lock target → ANOMALY DETECTED',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Test phases: gyro, magnetometer, quantum-link',
        '(spins needle 360°), calibrate, verify.',
        '',
        'COMMANDS',
        '--------',
        'qcp status      Show device status',
        'qcp firmware    Show firmware info',
        'qcp test        Run diagnostics',
        'qcp config      View configuration',
        'qcp mode        Cycle display mode',
        'qcp mode <name> Set specific mode',
        'qcp bearing <n> Set anomaly direction',
        'qcp distance <n> Set anomaly distance',
        'qcp reboot      Reboot device',
        '',
        'COMPATIBLE DEVICES',
        '------------------',
        'AND-001, DIM-001, QSM-001, EMC-001',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('dim001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'DIM-001 DIMENSION MONITOR',
        '===========================',
        'Type:     Dimensional Sensor',
        'Tier:     2',
        'Maker:    DIME (Dimensional Monitoring Electronics)',
        'Firmware: v1.0.0',
        '',
        'OVERVIEW',
        '--------',
        'Monitors dimensional stability and rift activity.',
        'Tracks D-space coordinates, Halo Plane proximity,',
        'and quantum entanglement strength in real time.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     1.5 E/s',
        'Idle:     0.8 E/s',
        'Standby:  0.1 E/s',
        'Category: Light',
        'Priority: 2',
        '',
        'FEATURES',
        '--------',
        '- D-space probe with dimensional lock',
        '- Rift activity scanner',
        '- Stability monitoring with threshold alerts',
        '- Halo Plane proximity detection',
        '- Quantum entanglement strength tracking',
        '- Auto-calibration system',
        '',
        'BOOT SEQUENCE',
        '-------------',
        'POST → Sensor init → Probe D-space → Calibrate',
        '→ Lock dimension → STABLE',
        '',
        'DIAGNOSTICS',
        '-----------',
        'Sensor test → Rift scan → Stability check',
        '→ Calibration verify → Complete',
        '',
        'COMMANDS',
        '--------',
        'dim status     - Device status',
        'dim firmware   - Firmware information',
        'dim test       - Run diagnostics',
        'dim config     - View configuration',
        'dim reboot     - Reboot device',
      ].join('\n'),
    }))
    this.addChild(opLocalDocs, this.mknode('btk001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'BTK-001 BASIC TOOLKIT',
        '===========================',
        'Type:     Hand Tool Array',
        'Tier:     1',
        'Maker:    HNDX (Handex Tools)',
        'Firmware: v1.2.0',
        '',
        'OVERVIEW',
        '--------',
        'Fundamental laboratory hand tool set. Four',
        'integrated tools: Probe, Clamp, Laser, Drill.',
        'Each tool independently calibrated and monitored.',
        '',
        'POWER SPECS',
        '-----------',
        'Full:     0.5 E/s',
        'Idle:     0.3 E/s',
        'Standby:  0.05 E/s',
        'Category: Light',
        'Priority: 2',
        '',
        'TOOLS',
        '-----',
        'PROBE   - Precision measurement probe',
        'CLAMP   - Adjustable grip clamp',
        'LASER   - Low-power cutting laser',
        'DRILL   - Variable-speed micro drill',
        '',
        'COMMANDS',
        '--------',
        'btk status     - Device status',
        'btk firmware   - Firmware information',
        'btk test       - Run diagnostics',
        'btk config     - View configuration',
        'btk tools      - Tool status',
        'btk reboot     - Reboot device',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('pwb001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        '═══════════════════════════════════════════════════════════',
        '  PWB-001 :: PORTABLE WORKBENCH',
        '  Device Specification v1.1',
        '═══════════════════════════════════════════════════════════',
        '',
        'OVERVIEW',
        '  Compact mobile workbench for prototyping and assembly.',
        '  3 crafting slots with auto-calibration. Supports',
        '  basic material processing and component assembly.',
        '',
        'SPECIFICATIONS',
        '  Device ID:     PWB-001',
        '  Firmware:      v1.1.0 (build 2026.01.25)',
        '  Checksum:      P3W8B1X5',
        '  Manufacturer:  FABX (Fabrication Systems)',
        '  Tier:          1',
        '  Crafting Slots: 3 (independent)',
        '',
        'POWER',
        '  Full:          3.0 E/s',
        '  Idle:          0.8 E/s',
        '  Standby:       0.15 E/s',
        '  Category:      Light',
        '  Priority:      P2',
        '',
        'FEATURES',
        '  - crafting-slots    : 3 independent crafting slots',
        '  - auto-calibration  : Automatic slot calibration system',
        '  - tool-tracking     : Tool tracking and management',
        '  - assembly-queue    : Assembly queue processing',
        '  - motor-clamp       : Motor-driven clamp system',
        '',
        'COMMANDS',
        '  pwb status           Show device status',
        '  pwb power [on|off]   Power on/off',
        '  pwb firmware         View firmware info',
        '  pwb firmware update  Check for firmware updates',
        '  pwb test             Run diagnostics',
        '  pwb reset            Reboot device',
        '  pwb config           View configuration',
        '  pwb slots            Slot status',
        '  pwb info             Show this documentation',
        '',
        'BOOT SEQUENCE',
        '  1. surface    - Calibrate work surface',
        '  2. clamps     - Initialize motor clamps',
        '  3. tools      - Load tool profiles',
        '  4. calibrate  - Auto-calibrate slots',
        '  5. ready      - Workbench online',
        '',
        'SHUTDOWN SEQUENCE',
        '  1. queue      - Complete assembly queue',
        '  2. release    - Release all clamps',
        '  3. cooldown   - Motor cooldown',
        '',
        'TROUBLESHOOTING',
        '  - Clamp failure: run pwb test to check motor alignment',
        '  - Calibration drift: run pwb reset to recalibrate',
        '  - Slot offline: check power draw with pwb status',
        '  - If device unresponsive: run pwb power off, then pwb power on',
        '',
        'COMPATIBLE DEVICES',
        '  MFR-001  Microfusion Reactor (power source)',
        '  QUA-001  Quantum Analyzer (material analysis)',
        '  IPL-001  Ion Pulse Laser (precision cutting)',
        '',
        '═══════════════════════════════════════════════════════════',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('tlp001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'TLP-001 TELEPORT PAD — User Manual',
        '====================================',
        'Manufacturer: WARP Industries',
        'Firmware: v2.2.0 | Build: 2025.08.10',
        '',
        'OVERVIEW',
        '  Quantum transport pad for inter-lab teleportation.',
        '  Uses capacitor-charged quantum lock for stable portal generation.',
        '  Supports 6 transport modes for various payload types.',
        '',
        'SPECIFICATIONS',
        '  Power Full:    35W (during transport)',
        '  Power Idle:     3W (standby monitoring)',
        '  Power Standby:  0.5W',
        '  Category:      Heavy',
        '  Priority:      4',
        '  Max Charge:    100%',
        '  Portal Types:  6 modes',
        '',
        'TRANSPORT MODES',
        '  STANDARD    — Balanced speed and stability',
        '  PRECISION   — High accuracy, slower transport',
        '  EXPRESS     — Fast transport, lower stability',
        '  STEALTH     — Low-signature transport',
        '  CARGO       — Heavy payload support',
        '  EMERGENCY   — Bypass safety, maximum speed',
        '',
        'TERMINAL COMMANDS',
        '  tlp                  Show status',
        '  tlp on / off         Power control',
        '  tlp test             Run diagnostics',
        '  tlp reboot           Restart device',
        '  tlp firmware         Show firmware info',
        '  tlp config           View/set configuration',
        '  tlp mode <mode>      Set transport mode',
        '  tlp charge           Show charge level',
        '  tlp dest             Show destination',
        '',
        'FIRMWARE FEATURES',
        '  capacitor-charge, matrix-align, quantum-lock,',
        '  coord-load, stabilize, portal-gen',
        '',
        'COMPATIBLE DEVICES',
        '  UEC-001  Energy Core (power source)',
        '  MFR-001  Microfusion Reactor (backup power)',
        '  DIM-001  Dimension Monitor (rift tracking)',
        '  QSM-001  Quantum State Monitor (entanglement)',
        '',
        'SAFETY WARNINGS',
        '  - Do not transport while charge < 20%',
        '  - Verify quantum lock before activation',
        '  - Emergency mode bypasses all safety checks',
        '  - Keep portal area clear during transport',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('lct001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'LCT-001 PRECISION LASER — User Manual',
        '=======================================',
        'Manufacturer: OPTX Industries',
        'Firmware: v2.1.0 | Build: 2025.07.20',
        '',
        'OVERVIEW',
        '  High-precision laser cutter for material processing.',
        '  Uses diode-array laser with active cooling and optics',
        '  calibration for sub-millimeter precision cutting.',
        '',
        'SPECIFICATIONS',
        '  Power Full:    25W (during cutting)',
        '  Power Idle:     4W (standby monitoring)',
        '  Power Standby:  0.5W',
        '  Category:      Heavy',
        '  Priority:      3',
        '  Max Power:     450W (laser output)',
        '  Precision:     ±0.01mm',
        '',
        'OPERATING MODES',
        '  CUTTING    — Standard material cutting',
        '  ENGRAVING  — Surface marking with depth control',
        '  WELDING    — Point/seam welding operations',
        '  MARKING    — Low-power identification marking',
        '  DRILLING   — Precision hole drilling',
        '  SCANNING   — Non-contact surface scanning',
        '',
        'TERMINAL COMMANDS',
        '  lct                  Show status',
        '  lct on / off         Power control',
        '  lct test             Run diagnostics',
        '  lct reboot           Restart device',
        '  lct firmware         Show firmware info',
        '  lct config           View/set configuration',
        '  lct mode <mode>      Set operating mode',
        '  lct power <watts>    Set laser power (0-450)',
        '  lct precision <mm>   Set precision (0.001-1.0)',
        '',
        'FIRMWARE FEATURES',
        '  diode-array, optics-check, focus-calibrate,',
        '  power-regulate, thermal-protect, precision-cut',
        '',
        'COMPATIBLE DEVICES',
        '  UEC-001  Energy Core (power source)',
        '  MFR-001  Microfusion Reactor (backup power)',
        '  DIM-001  Dimension Monitor (material analysis)',
        '  QSM-001  Quantum State Monitor (precision boost)',
        '',
        'SAFETY WARNINGS',
        '  - Never look directly at the laser beam',
        '  - Ensure cooling system is operational',
        '  - Keep work area clear of flammable materials',
        '  - Disable laser before maintenance',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('p3d001.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        'P3D-001 3D FABRICATOR — User Manual',
        '=====================================',
        'Manufacturer: PRSA Industries',
        'Firmware: v3.2.1 | Build: 2025.06.15',
        '',
        'OVERVIEW',
        '  Additive manufacturing unit for complex part fabrication.',
        '  Supports plastic, metal, crystal and composite materials.',
        '  Features auto-leveling bed and multi-material extrusion.',
        '',
        'SPECIFICATIONS',
        '  Power Full:    18W (during printing)',
        '  Power Idle:     3W (standby monitoring)',
        '  Power Standby:  0.5W',
        '  Category:      Heavy',
        '  Priority:      3',
        '  Bed Temp:      0-120°C',
        '  Materials:     6 modes',
        '',
        'MATERIAL MODES',
        '  PLASTIC     — Standard thermoplastic extrusion',
        '  METAL       — Sintered metal powder fabrication',
        '  CRYSTAL     — Crystalline lattice growth',
        '  COMPOSITE   — Multi-material layered construction',
        '  NANO        — Nanoscale precision printing',
        '  PROTOTYPE   — Rapid prototyping mode',
        '',
        'TERMINAL COMMANDS',
        '  p3d                  Show status',
        '  p3d on / off         Power control',
        '  p3d test             Run diagnostics',
        '  p3d reboot           Restart device',
        '  p3d firmware         Show firmware info',
        '  p3d config           View/set configuration',
        '  p3d mode <mode>      Set material mode',
        '  p3d progress <pct>   Set print progress (0-100)',
        '  p3d layer <num>      Set layer count',
        '  p3d bedtemp <°C>     Set bed temperature (0-120)',
        '',
        'FIRMWARE FEATURES',
        '  bed-level, nozzle-calibrate, extrusion-ctrl,',
        '  layer-track, thermal-manage, multi-material',
        '',
        'COMPATIBLE DEVICES',
        '  PWB-001  Portable Workbench (assembly)',
        '  MSC-001  Material Scanner (analysis)',
        '  LCT-001  Precision Laser (post-processing)',
        '  BTK-001  Toolkit (maintenance)',
        '',
        'SAFETY WARNINGS',
        '  - Hot bed surface — do not touch during operation',
        '  - Allow cooling before removing prints',
        '  - Keep nozzle clear of obstructions',
        '  - Ventilate area when printing metal/composite',
      ].join('\n'),
    }))

    this.addChild(opLocalDocs, this.mknode('screwbuttons.txt', 'file', {
      owner: 'operator', group: 'operator',
      content: [
        '═══════════════════════════════════════════════════════════',
        '  SCREW BUTTON SYSTEM :: MULTIPLAYER FEATURES',
        '  System Specification v1.0',
        '═══════════════════════════════════════════════════════════',
        '',
        'OVERVIEW',
        '  Four hidden screw buttons on the terminal bezel provide',
        '  access to collaborative multiplayer features. Long-press',
        '  (2 seconds) a screw to toggle activation.',
        '',
        'BUTTONS',
        '  SB-01  Top-Left      NODE-SYNC       Network Node Sync',
        '  SB-02  Top-Right     POOL-LINK       Mining Pool Linkage',
        '  SB-03  Bottom-Left   MESH-CAST       Memetic Broadcasting',
        '  SB-04  Bottom-Right  QUANTUM-BRIDGE  Dimensional Bridge',
        '',
        'COMMANDS',
        '  screwstat              Overview of all screw buttons',
        '  nodesync [sub]         NODE-SYNC control (SB-01)',
        '  poollink [sub]         POOL-LINK control (SB-02)',
        '  meshcast [sub]         MESH-CAST control (SB-03)',
        '  qbridge  [sub]         QUANTUM-BRIDGE control (SB-04)',
        '',
        'ACTIVATION',
        '  - Long-press screw on bezel (2 seconds)',
        '  - Or use terminal: nodesync enable',
        '  - LED ring: red=charging, amber=activating, green=active',
        '',
        '═══════════════════════════════════════════════════════════',
      ].join('\n'),
    }))

    const opCrystals = this.addChild(opHome, this.mknode('crystals', 'dir', { owner: 'operator', group: 'operator' }))
    this.addChild(opCrystals, this.mknode('.gitkeep', 'file', { owner: 'operator', group: 'operator', content: '' }))
    const opScripts = this.addChild(opHome, this.mknode('scripts', 'dir', { owner: 'operator', group: 'operator' }))
    this.addChild(opScripts, this.mknode('scan.sh', 'file', {
      owner: 'operator', group: 'operator', permissions: 0o755,
      content: '#!/bin/sh\n# Volatility scanner script\necho "Scanning blockchain for TPS data..."\nscan\n',
    }))

    // /home/adm
    const admHome = this.addChild(home, this.mknode('adm', 'dir', { owner: 'adm', group: 'adm', permissions: 0o750 }))
    this.addChild(admHome, this.mknode('.bashrc', 'file', {
      owner: 'adm', group: 'adm',
      content: '# _unOS admin shell config\nexport PS1="\\u@_unLAB:\\w$ "\nexport PATH=/bin:/usr/bin:/sbin\n',
    }))
    this.addChild(admHome, this.mknode('.profile', 'file', {
      owner: 'adm', group: 'adm',
      content: '# adm profile\necho "Welcome, administrator."\n',
    }))
    this.addChild(admHome, this.mknode('notes.txt', 'file', {
      owner: 'adm', group: 'adm',
      content: '# Admin Notes\n- Root escalation via su requires wheel group membership\n- Monitor /var/log/auth.log for unauthorized access\n- Crystal stability reports in /srv/_unLAB/reports/\n',
    }))

    // /srv/_unLAB
    const srv = this.addChild(root, this.mknode('srv', 'dir'))
    const srvLab = this.addChild(srv, this.mknode('_unLAB', 'dir'))
    const srvData = this.addChild(srvLab, this.mknode('data', 'dir'))
    this.addChild(srvData, this.mknode('.gitkeep', 'file', { content: '' }))
    const srvReports = this.addChild(srvLab, this.mknode('reports', 'dir'))
    this.addChild(srvReports, this.mknode('stability.log', 'file', {
      content: '[2026-01-28 00:00:00] Crystal stability check: ALL NOMINAL\n[2026-01-28 00:05:00] Volatility tier: 2 (TPS: 1847)\n',
    }))
    this.addChild(srvLab, this.mknode('config', 'dir'))

    // /usr
    const usr = this.addChild(root, this.mknode('usr', 'dir'))
    const usrBin = this.addChild(usr, this.mknode('bin', 'dir'))
    this.addChild(usrBin, this.mknode('crystal-cli', 'file', { permissions: 0o755, content: '#!/bin/sh\n# Crystal management CLI\n' }))
    const usrLib = this.addChild(usr, this.mknode('lib', 'dir'))
    this.addChild(usrLib, this.mknode('libcrystal.so', 'file', { content: '<binary>' }))
    const usrShare = this.addChild(usr, this.mknode('share', 'dir'))
    const usrDoc = this.addChild(usrShare, this.mknode('doc', 'dir'))
    this.addChild(usrDoc, this.mknode('README', 'file', { content: '_unOS - Unstable Laboratories Operating System\nVersion 2.1.0\n' }))

    // /var
    const varDir = this.addChild(root, this.mknode('var', 'dir'))
    const varLog = this.addChild(varDir, this.mknode('log', 'dir'))
    const varLogUnos = this.addChild(varLog, this.mknode('_unOS', 'dir'))
    this.addChild(varLogUnos, this.mknode('system.log', 'file', {
      content: '[2026-01-28 00:00:00] _unOS kernel initialized\n[2026-01-28 00:00:01] All subsystems online\n',
    }))
    this.addChild(varLogUnos, this.mknode('crystal.log', 'file', {
      content: '[2026-01-28 00:00:02] Crystal data cache loaded\n',
    }))
    this.addChild(varLogUnos, this.mknode('screwbutton.log', 'file', {
      content: '[2026-01-28 00:00:03] ScrewButton subsystem initialized\n[2026-01-28 00:00:03] 4 buttons registered: SB-01, SB-02, SB-03, SB-04\n',
    }))
    this.addChild(varLogUnos, this.mknode('rmg.log', 'file', {
      content: [
        '[2024-03-15 08:00:01] RMG-001 boot: POST check passed',
        '[2024-03-15 08:00:01] RMG-001 boot: Coil check OK',
        '[2024-03-15 08:00:02] RMG-001 boot: Flux generator online',
        '[2024-03-15 08:00:02] RMG-001 boot: Field initialized',
        '[2024-03-15 08:00:03] RMG-001 boot: Calibration complete',
        '[2024-03-15 08:00:03] RMG-001 status: ONLINE',
        '[2024-03-15 10:45:10] RMG-001 diag: Coils PASS',
        '[2024-03-15 10:45:11] RMG-001 diag: Field PASS',
        '[2024-03-15 10:45:11] RMG-001 diag: Flux PASS',
        '[2024-03-15 10:45:12] RMG-001 diag: Calibration PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('msc.log', 'file', {
      content: [
        '[2024-02-28 09:00:01] MSC-001 boot: POST check passed',
        '[2024-02-28 09:00:01] MSC-001 boot: Sensor init OK',
        '[2024-02-28 09:00:02] MSC-001 boot: Calibration complete',
        '[2024-02-28 09:00:02] MSC-001 status: SCANNING',
        '[2024-02-28 11:30:05] MSC-001 diag: Emitter PASS',
        '[2024-02-28 11:30:05] MSC-001 diag: Receiver PASS',
        '[2024-02-28 11:30:06] MSC-001 diag: Calibration PASS',
        '[2024-02-28 11:30:06] MSC-001 diag: Sweep PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('tmp.log', 'file', {
      content: [
        '[2024-03-01 06:00:01] TMP-001 boot: POST check passed',
        '[2024-03-01 06:00:01] TMP-001 boot: Sensor init — 3 probes OK',
        '[2024-03-01 06:00:02] TMP-001 boot: Calibration complete',
        '[2024-03-01 06:00:02] TMP-001 boot: Reading temps — 26.3°C',
        '[2024-03-01 06:00:02] TMP-001 status: NOMINAL',
        '[2024-03-01 14:20:10] TMP-001 diag: Sensor PASS',
        '[2024-03-01 14:20:11] TMP-001 diag: Calibration PASS',
        '[2024-03-01 14:20:11] TMP-001 diag: Threshold PASS',
        '[2024-03-01 14:20:12] TMP-001 diag: Cooling PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('net.log', 'file', {
      content: [
        '[2024-03-15 07:00:01] NET-001 boot: POST check passed',
        '[2024-03-15 07:00:01] NET-001 boot: NIC detected — eth0',
        '[2024-03-15 07:00:02] NET-001 boot: DHCP lease acquired',
        '[2024-03-15 07:00:02] NET-001 boot: Handshake OK',
        '[2024-03-15 07:00:03] NET-001 boot: Routes synced',
        '[2024-03-15 07:00:03] NET-001 status: CONNECTED',
        '[2024-03-15 10:15:20] NET-001 diag: Latency PASS (12ms)',
        '[2024-03-15 10:15:21] NET-001 diag: Bandwidth PASS (2.4 Gbps)',
        '[2024-03-15 10:15:21] NET-001 diag: Packet integrity PASS',
        '[2024-03-15 10:15:22] NET-001 diag: Security check PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('clk.log', 'file', {
      content: [
        '[2024-02-28 00:00:01] CLK-001 boot: Crystal init OK (32.768 kHz)',
        '[2024-02-28 00:00:01] CLK-001 boot: RTC synced',
        '[2024-02-28 00:00:02] CLK-001 boot: NTP query OK (time.unos.local)',
        '[2024-02-28 00:00:02] CLK-001 boot: Drift compensation active',
        '[2024-02-28 00:00:03] CLK-001 status: SYNCED',
        '[2024-02-28 09:00:00] CLK-001 ntp: Re-sync OK, drift +0.003s',
        '[2024-02-28 18:00:00] CLK-001 ntp: Re-sync OK, drift -0.001s',
        '[2024-02-28 23:15:00] CLK-001 diag: Crystal PASS',
        '[2024-02-28 23:15:01] CLK-001 diag: Sync PASS',
        '[2024-02-28 23:15:01] CLK-001 diag: Drift PASS',
        '[2024-02-28 23:15:02] CLK-001 diag: Accuracy PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('cpu.log', 'file', {
      content: [
        '[2024-03-01 08:00:01] CPU-001 boot: POST check passed',
        '[2024-03-01 08:00:01] CPU-001 boot: 8 cores detected',
        '[2024-03-01 08:00:02] CPU-001 boot: L1/L2 cache init OK',
        '[2024-03-01 08:00:02] CPU-001 boot: Freq scaling to 4.2 GHz',
        '[2024-03-01 08:00:03] CPU-001 boot: Calibration complete',
        '[2024-03-01 08:00:03] CPU-001 status: READY',
        '[2024-03-01 12:15:00] CPU-001 diag: Core test PASS',
        '[2024-03-01 12:15:01] CPU-001 diag: Cache integrity PASS',
        '[2024-03-01 12:15:02] CPU-001 diag: Freq validation PASS',
        '[2024-03-01 12:15:03] CPU-001 diag: Thermal check PASS',
        '[2024-03-01 12:15:04] CPU-001 diag: Stress test PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('mem.log', 'file', {
      content: [
        '[2024-03-01 08:00:01] MEM-001 boot: DIMM detect — 4 slots',
        '[2024-03-01 08:00:01] MEM-001 boot: SPD read OK (DDR5-5600)',
        '[2024-03-01 08:00:02] MEM-001 boot: Timing config applied',
        '[2024-03-01 08:00:02] MEM-001 boot: Memory test 16384 MB OK',
        '[2024-03-01 08:00:03] MEM-001 boot: Memory mapped',
        '[2024-03-01 08:00:03] MEM-001 status: READY',
        '[2024-03-01 14:00:00] MEM-001 diag: Module test PASS',
        '[2024-03-01 14:00:01] MEM-001 diag: Timing check PASS',
        '[2024-03-01 14:00:02] MEM-001 diag: Integrity PASS',
        '[2024-03-01 14:00:03] MEM-001 diag: Bandwidth PASS',
        '[2024-03-01 14:00:04] MEM-001 diag: Stress test PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('qcp.log', 'file', {
      content: [
        '[2024-03-12 10:00:01] QCP-001 boot: Gyro init OK',
        '[2024-03-12 10:00:01] QCP-001 boot: Magnetometer calibrated',
        '[2024-03-12 10:00:02] QCP-001 boot: Quantum link established',
        '[2024-03-12 10:00:02] QCP-001 boot: Calibration complete',
        '[2024-03-12 10:00:03] QCP-001 boot: Target locked at 127° / 42m',
        '[2024-03-12 10:00:03] QCP-001 status: ANOMALY DETECTED',
        '[2024-03-12 15:22:10] QCP-001 bearing: Anomaly shifted to 145°',
        '[2024-03-12 15:22:11] QCP-001 distance: Range closing — 38m',
        '[2024-03-12 20:00:00] QCP-001 diag: Gyro test PASS',
        '[2024-03-12 20:00:01] QCP-001 diag: Magnetometer PASS',
        '[2024-03-12 20:00:02] QCP-001 diag: Quantum link PASS',
        '[2024-03-12 20:00:03] QCP-001 diag: Calibration PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('and.log', 'file', {
      content: [
        '[2024-03-10 09:00:01] AND-001 boot: Sensor init OK',
        '[2024-03-10 09:00:01] AND-001 boot: Calibration complete',
        '[2024-03-10 09:00:02] AND-001 boot: Freq sweep 0-100MHz',
        '[2024-03-10 09:00:02] AND-001 boot: Scanning active',
        '[2024-03-10 09:00:03] AND-001 boot: Analysis engine ready',
        '[2024-03-10 09:00:03] AND-001 status: SCANNING',
        '[2024-03-10 12:15:44] AND-001 alert: Anomaly detected at 67% signal',
        '[2024-03-10 12:15:45] AND-001 alert: Classification — dimensional rift',
        '[2024-03-10 18:00:00] AND-001 diag: Sensor test PASS',
        '[2024-03-10 18:00:01] AND-001 diag: Calibration PASS',
        '[2024-03-10 18:00:02] AND-001 diag: Full sweep PASS',
        '[2024-03-10 18:00:03] AND-001 diag: Analysis engine PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('dim.log', 'file', {
      content: [
        '[2024-03-05 06:00:01] DIM-001 boot: POST check passed',
        '[2024-03-05 06:00:01] DIM-001 boot: Sensor init complete',
        '[2024-03-05 06:00:02] DIM-001 boot: D-space probe online',
        '[2024-03-05 06:00:02] DIM-001 boot: Rift calibration OK',
        '[2024-03-05 06:00:03] DIM-001 boot: Dimension locked at D-3.14',
        '[2024-03-05 06:00:03] DIM-001 status: STABLE',
        '[2024-03-05 14:30:10] DIM-001 diag: Sensor array PASS',
        '[2024-03-05 14:30:11] DIM-001 diag: Rift scan PASS',
        '[2024-03-05 14:30:12] DIM-001 diag: Stability check PASS',
        '[2024-03-05 14:30:12] DIM-001 diag: Calibration PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('btk.log', 'file', {
      content: [
        '[2024-03-10 08:00:01] BTK-001 boot: POST check passed',
        '[2024-03-10 08:00:01] BTK-001 boot: Tool init complete',
        '[2024-03-10 08:00:02] BTK-001 boot: Interface ready',
        '[2024-03-10 08:00:02] BTK-001 status: ONLINE',
        '[2024-03-10 09:30:15] BTK-001 diag: Probe PASS',
        '[2024-03-10 09:30:16] BTK-001 diag: Clamp PASS',
        '[2024-03-10 09:30:17] BTK-001 diag: Laser PASS',
        '[2024-03-10 09:30:17] BTK-001 diag: Drill PASS',
        '[2024-03-10 09:30:18] BTK-001 diag: Calibration PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('pwb.log', 'file', {
      content: [
        '[2024-02-20 08:00:01] PWB-001 boot: POST check passed',
        '[2024-02-20 08:00:02] PWB-001 boot: Firmware v1.1.0 verified',
        '[2024-02-20 08:00:02] PWB-001 boot: Surface calibration OK',
        '[2024-02-20 08:00:03] PWB-001 boot: Tool init complete',
        '[2024-02-20 08:00:03] PWB-001 status: ONLINE',
        '[2024-02-20 09:15:22] PWB-001 diag: Motor alignment PASS',
        '[2024-02-20 09:15:23] PWB-001 diag: Clamp integrity PASS',
        '[2024-02-20 09:15:24] PWB-001 diag: Sensor check PASS',
        '[2024-02-20 09:15:24] PWB-001 diag: Calibration PASS',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('tlp.log', 'file', {
      content: [
        '[2025-08-10 09:00:00] TLP-001 firmware v2.2.0 loaded',
        '[2025-08-10 09:00:01] Capacitor bank initialized',
        '[2025-08-10 09:00:02] Matrix alignment: nominal',
        '[2025-08-10 09:00:03] Quantum lock calibrated',
        '[2025-08-10 09:00:04] Portal generator online',
        '[2025-08-10 09:01:00] Transport mode: STANDARD',
        '[2025-08-10 09:05:00] Charge level: 65%',
        '[2025-08-10 09:10:00] Destination locked: LAB-Ω',
        '[2025-08-10 10:00:00] Self-test: PASSED',
        '[2025-08-10 12:00:00] Coordinates verified',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('p3d.log', 'file', {
      content: [
        '[2025-06-15 09:00:00] P3D-001 firmware v3.2.1 loaded',
        '[2025-06-15 09:00:01] Bed heater initialized',
        '[2025-06-15 09:00:02] Axes homing: complete',
        '[2025-06-15 09:00:03] Nozzle calibrated',
        '[2025-06-15 09:00:04] Extruder online',
        '[2025-06-15 09:01:00] Material mode: PLASTIC',
        '[2025-06-15 09:05:00] Print progress: 67%',
        '[2025-06-15 09:10:00] Layer count: 234',
        '[2025-06-15 10:00:00] Self-test: PASSED',
        '[2025-06-15 12:00:00] Bed temperature stable at 60°C',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('lct.log', 'file', {
      content: [
        '[2025-07-20 09:00:00] LCT-001 firmware v2.1.0 loaded',
        '[2025-07-20 09:00:01] Diode array initialized',
        '[2025-07-20 09:00:02] Cooling system: nominal',
        '[2025-07-20 09:00:03] Optics calibrated',
        '[2025-07-20 09:00:04] Laser emitter online',
        '[2025-07-20 09:01:00] Operating mode: CUTTING',
        '[2025-07-20 09:05:00] Laser power: 450W',
        '[2025-07-20 09:10:00] Precision: ±0.01mm',
        '[2025-07-20 10:00:00] Self-test: PASSED',
        '[2025-07-20 12:00:00] Focus point verified',
      ].join('\n'),
    }))
    this.addChild(varLogUnos, this.mknode('network-sync.log', 'file', {
      content: '[2026-01-28 00:00:04] Network sync daemon started\n[2026-01-28 00:00:05] Awaiting node-sync activation...\n',
    }))
    this.addChild(varLog, this.mknode('auth.log', 'file', {
      permissions: 0o640,
      content: '[2026-01-28 00:00:00] operator logged in from terminal\n',
    }))

    // /tmp
    this.addChild(root, this.mknode('tmp', 'dir', { permissions: 0o1777 }))

    // /root
    this.addChild(root, this.mknode('root', 'dir', { permissions: 0o700 }))

    return root
  }

  resolve(path: string): VirtualNode | null {
    const absPath = this.toAbsolute(path)
    if (absPath === '/') return this.root

    const parts = absPath.split('/').filter(Boolean)
    let current = this.root

    for (const part of parts) {
      if (current.type !== 'dir' || !current.children) return null
      const child = current.children.get(part)
      if (!child) return null
      if (child.type === 'symlink' && child.target) {
        const resolved = this.resolve(child.target)
        if (!resolved) return null
        current = resolved
      } else {
        current = child
      }
    }
    return current
  }

  toAbsolute(path: string): string {
    if (path === '~') return this.getHomeDirForUser()
    if (path.startsWith('~/')) return this.getHomeDirForUser() + path.slice(1)
    if (path.startsWith('/')) return this.normalizePath(path)
    return this.normalizePath(this._cwd + '/' + path)
  }

  private _homeUser: string = 'operator'
  setHomeUser(username: string) {
    this._homeUser = username
  }

  private getHomeDirForUser(): string {
    if (this._homeUser === 'root') return '/root'
    return `/home/${this._homeUser}`
  }

  private normalizePath(path: string): string {
    const parts = path.split('/').filter(Boolean)
    const resolved: string[] = []
    for (const part of parts) {
      if (part === '.') continue
      if (part === '..') {
        resolved.pop()
      } else {
        resolved.push(part)
      }
    }
    return '/' + resolved.join('/')
  }

  checkPermission(node: VirtualNode, user: string, groups: string[], action: 'r' | 'w' | 'x'): boolean {
    if (user === 'root') return true
    const perm = node.permissions
    const bitIndex = action === 'r' ? 2 : action === 'w' ? 1 : 0

    if (node.owner === user) {
      return Boolean((perm >> (6 + bitIndex)) & 1)
    }
    if (groups.includes(node.group)) {
      return Boolean((perm >> (3 + bitIndex)) & 1)
    }
    return Boolean((perm >> bitIndex) & 1)
  }

  formatPermissions(node: VirtualNode): string {
    const typeChar = node.type === 'dir' ? 'd' : node.type === 'symlink' ? 'l' : '-'
    const p = node.permissions
    const bits = [
      (p >> 8) & 1 ? 'r' : '-', (p >> 7) & 1 ? 'w' : '-', (p >> 6) & 1 ? 'x' : '-',
      (p >> 5) & 1 ? 'r' : '-', (p >> 4) & 1 ? 'w' : '-', (p >> 3) & 1 ? 'x' : '-',
      (p >> 2) & 1 ? 'r' : '-', (p >> 1) & 1 ? 'w' : '-', (p >> 0) & 1 ? 'x' : '-',
    ]
    return typeChar + bits.join('')
  }

  ls(path?: string, flags: { long?: boolean; all?: boolean } = {}): string[] {
    const targetPath = path || this._cwd
    const node = this.resolve(targetPath)
    if (!node) return [`ls: cannot access '${targetPath}': No such file or directory`]
    if (node.type !== 'dir') {
      if (flags.long) {
        return [this.formatLongEntry(node)]
      }
      return [node.name]
    }

    const entries = Array.from(node.children!.entries())
      .filter(([name]) => flags.all || !name.startsWith('.'))
      .sort(([a], [b]) => a.localeCompare(b))

    if (entries.length === 0) return []

    if (flags.long) {
      return entries.map(([, child]) => this.formatLongEntry(child))
    }

    return entries.map(([, child]) => {
      if (child.type === 'dir') return `\x1b[36m${child.name}/\x1b[0m`
      if (child.type === 'symlink') return `\x1b[35m${child.name}\x1b[0m`
      if ((child.permissions & 0o111) !== 0) return `\x1b[32m${child.name}\x1b[0m`
      return child.name
    })
  }

  private formatLongEntry(node: VirtualNode): string {
    const perms = this.formatPermissions(node)
    const owner = node.owner.padEnd(10)
    const group = node.group.padEnd(10)
    const size = node.size.toString().padStart(6)
    const date = new Date(node.modified).toLocaleDateString('en-US', { month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' })
    const name = node.type === 'dir' ? `\x1b[36m${node.name}/\x1b[0m` :
                 node.type === 'symlink' ? `\x1b[35m${node.name} -> ${node.target}\x1b[0m` :
                 (node.permissions & 0o111) !== 0 ? `\x1b[32m${node.name}\x1b[0m` :
                 node.name
    return `${perms} ${owner} ${group} ${size} ${date} ${name}`
  }

  cd(path: string): string | null {
    const target = path === '-' ? this._previousCwd : path
    const absPath = this.toAbsolute(target)
    const node = this.resolve(absPath)
    if (!node) return `cd: ${path}: No such file or directory`
    if (node.type !== 'dir') return `cd: ${path}: Not a directory`
    this._previousCwd = this._cwd
    this._cwd = absPath
    return null
  }

  pwd(): string {
    return this._cwd
  }

  cat(path: string): string | null {
    const node = this.resolve(path)
    if (!node) return `cat: ${path}: No such file or directory`
    if (node.type === 'dir') return `cat: ${path}: Is a directory`
    return node.content ?? ''
  }

  mkdir(path: string, parents: boolean = false): string | null {
    const absPath = this.toAbsolute(path)
    const parts = absPath.split('/').filter(Boolean)
    let current = this.root

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]
      if (!current.children) return `mkdir: cannot create '${path}': Not a directory`

      const existing = current.children.get(part)
      if (existing) {
        if (existing.type !== 'dir') return `mkdir: cannot create '${path}': File exists`
        if (i === parts.length - 1 && !parents) return `mkdir: cannot create '${path}': File exists`
        current = existing
      } else {
        if (i < parts.length - 1 && !parents) return `mkdir: cannot create '${path}': No such file or directory`
        const newDir = this.mknode(part, 'dir', { owner: this._homeUser, group: this._homeUser })
        this.addChild(current, newDir)
        current = newDir
      }
    }
    return null
  }

  touch(path: string): string | null {
    const absPath = this.toAbsolute(path)
    const parts = absPath.split('/').filter(Boolean)
    const fileName = parts.pop()
    if (!fileName) return `touch: missing file operand`

    const parentPath = '/' + parts.join('/')
    const parent = this.resolve(parentPath)
    if (!parent) return `touch: cannot touch '${path}': No such file or directory`
    if (parent.type !== 'dir') return `touch: cannot touch '${path}': Not a directory`

    const existing = parent.children!.get(fileName)
    if (existing) {
      existing.modified = Date.now()
      return null
    }

    const file = this.mknode(fileName, 'file', { owner: this._homeUser, group: this._homeUser, content: '' })
    this.addChild(parent, file)
    return null
  }

  rm(path: string, recursive: boolean = false): string | null {
    const absPath = this.toAbsolute(path)
    if (absPath === '/') return `rm: cannot remove '/': Permission denied`

    const parts = absPath.split('/').filter(Boolean)
    const name = parts.pop()
    if (!name) return `rm: missing operand`

    const parentPath = '/' + parts.join('/')
    const parent = this.resolve(parentPath)
    if (!parent || !parent.children) return `rm: cannot remove '${path}': No such file or directory`

    const target = parent.children.get(name)
    if (!target) return `rm: cannot remove '${path}': No such file or directory`
    if (target.type === 'dir' && !recursive) return `rm: cannot remove '${path}': Is a directory (use -r)`
    if (target.type === 'dir' && target.children && target.children.size > 0 && !recursive) {
      return `rm: cannot remove '${path}': Directory not empty`
    }

    parent.children.delete(name)
    return null
  }

  tree(path?: string, depth: number = 3): string[] {
    const targetPath = path || this._cwd
    const node = this.resolve(targetPath)
    if (!node) return [`${targetPath} [error opening dir]`]
    if (node.type !== 'dir') return [node.name]

    const lines: string[] = [targetPath]
    this.buildTree(node, '', depth, lines)
    return lines
  }

  private buildTree(node: VirtualNode, prefix: string, depth: number, lines: string[]): void {
    if (depth <= 0 || node.type !== 'dir' || !node.children) return

    const entries = Array.from(node.children.entries())
      .filter(([name]) => !name.startsWith('.'))
      .sort(([a], [b]) => a.localeCompare(b))

    entries.forEach(([, child], i) => {
      const isLast = i === entries.length - 1
      const connector = isLast ? '└── ' : '├── '
      const name = child.type === 'dir' ? `\x1b[36m${child.name}/\x1b[0m` : child.name
      lines.push(prefix + connector + name)
      if (child.type === 'dir') {
        this.buildTree(child, prefix + (isLast ? '    ' : '│   '), depth - 1, lines)
      }
    })
  }

  stat(path: string): VirtualNode | null {
    return this.resolve(path)
  }

  chmod(path: string, mode: number): string | null {
    const node = this.resolve(path)
    if (!node) return `chmod: cannot access '${path}': No such file or directory`
    node.permissions = mode
    return null
  }

  chown(path: string, owner: string): string | null {
    const node = this.resolve(path)
    if (!node) return `chown: cannot access '${path}': No such file or directory`
    node.owner = owner
    return null
  }

  toJSON(): string {
    return JSON.stringify({
      cwd: this._cwd,
      previousCwd: this._previousCwd,
      homeUser: this._homeUser,
      tree: this.serializeNode(this.root),
    })
  }

  private serializeNode(node: VirtualNode): Record<string, unknown> {
    const obj: Record<string, unknown> = {
      n: node.name,
      t: node.type,
      p: node.permissions,
      o: node.owner,
      g: node.group,
      m: node.modified,
      s: node.size,
    }
    if (node.content !== undefined) obj.c = node.content
    if (node.target) obj.tg = node.target
    if (node.children) {
      const ch: Record<string, unknown> = {}
      for (const [k, v] of node.children) {
        ch[k] = this.serializeNode(v)
      }
      obj.ch = ch
    }
    return obj
  }

  static fromJSON(json: string): VirtualFS {
    const fs = new VirtualFS()
    try {
      const data = JSON.parse(json)
      fs._cwd = data.cwd || '/home/operator'
      fs._previousCwd = data.previousCwd || '/home/operator'
      fs._homeUser = data.homeUser || 'operator'
      if (data.tree) {
        fs.root = fs.deserializeNode(data.tree)
      }
    } catch {
      // Return default FS on parse error
    }
    return fs
  }

  private deserializeNode(obj: Record<string, unknown>): VirtualNode {
    const node: VirtualNode = {
      name: obj.n as string,
      type: obj.t as 'file' | 'dir' | 'symlink',
      permissions: obj.p as number,
      owner: obj.o as string,
      group: obj.g as string,
      modified: obj.m as number,
      size: obj.s as number,
    }
    if (obj.c !== undefined) node.content = obj.c as string
    if (obj.tg) node.target = obj.tg as string
    if (obj.ch) {
      node.children = new Map()
      for (const [k, v] of Object.entries(obj.ch as Record<string, unknown>)) {
        node.children.set(k, this.deserializeNode(v as Record<string, unknown>))
      }
    }
    return node
  }
}
