import { Palette } from "@/lib/voxel/palette";
import type { MaterialClass } from "@/lib/voxel/mesher";

/**
 * The lab palette. Colors follow the UI style guide (panel darks, neon
 * spectrum, CRT phosphor); every entry maps to one render class.
 */
const ENTRIES = {
  floor_dark: ["#2a2d31", "solid"],
  floor_tile: ["#3a3f45", "solid"],
  floor_grate: ["#4a4f55", "metal"],
  wall: ["#5b6068", "solid"],
  wall_dark: ["#3d4147", "solid"],
  wall_trim: ["#FFB800", "solid"],
  floor_green: ["#2f3b33", "solid"],
  floor_blue: ["#28323f", "solid"],
  floor_red: ["#3b2a2a", "solid"],
  floor_purple: ["#2e2838", "solid"],
  floor_beige: ["#4a463c", "solid"],
  wall_beige: ["#8a816c", "solid"],
  wall_olive: ["#4A5040", "solid"],
  wall_teal: ["#2D6B6B", "solid"],
  door_frame: ["#FFB800", "metal"],
  door_locked: ["#FF3333", "emit"],
  door_panel: ["#3D3D3D", "metal"],
  metal: ["#3D3D3D", "metal"],
  metal_light: ["#6b7078", "metal"],
  metal_dark: ["#1f2226", "metal"],
  black: ["#0D0D0D", "solid"],
  screen_green: ["#33FF33", "emit"],
  screen_amber: ["#FFAA00", "emit"],
  screen_cyan: ["#00FFFF", "emit"],
  led_red: ["#FF3333", "emit"],
  led_green: ["#00FF66", "emit"],
  led_amber: ["#FFB800", "emit"],
  neon_pink: ["#FF00FF", "emit"],
  neon_magenta: ["#E91E8C", "emit"],
  neon_purple: ["#8B00FF", "emit"],
  neon_blue: ["#0066FF", "emit"],
  glass: ["#9fd8ff", "glass"],
  glass_green: ["#7dffb0", "glass"],
  glass_purple: ["#c38bff", "glass"],
  copper: ["#b8733a", "metal"],
  brass: ["#c9a227", "metal"],
  white: ["#e8e8e2", "solid"],
  beige: ["#C4B9A0", "solid"],
  olive: ["#4A5040", "solid"],
  teal: ["#2D6B6B", "solid"],
  red_paint: ["#b8322b", "solid"],
  orange_paint: ["#e0661a", "solid"],
  blue_paint: ["#2a5db0", "solid"],
  purple_paint: ["#5b2a9a", "solid"],
  green_paint: ["#2f8a4a", "solid"],
  yellow_paint: ["#d9b21e", "solid"],
  wood: ["#7a5230", "solid"],
  wood_dark: ["#4d321c", "solid"],
  cardboard: ["#a07c4c", "solid"],
  paper: ["#efe8d0", "solid"],
  skin: ["#e0b18f", "solid"],
  skin_shadow: ["#c48f6c", "solid"],
  hair_auburn: ["#7a3a22", "solid"],
  hair_gray: ["#9a9a9a", "solid"],
  coat_white: ["#f2f2ee", "solid"],
  coat_shadow: ["#c9ccd0", "solid"],
  pants_dark: ["#2b2f3a", "solid"],
  shoes: ["#1a1a1a", "solid"],
  goggles: ["#FFB800", "metal"],
  vest_brown: ["#5a4430", "solid"],
  holo_cyan: ["#00FFFF", "glass"],
  holo_white: ["#e0ffff", "glass"],
  plant_green: ["#3f8f3f", "solid"],
  pot: ["#8a4b2a", "solid"],
  cable_black: ["#151515", "solid"],
  cable_red: ["#8a1f1f", "solid"],
  cable_yellow: ["#b58b10", "solid"],
  plasma: ["#ff7a1a", "emit"],
  plasma_blue: ["#6ad4ff", "emit"],
  abstractum: ["#b060ff", "emit"],
  exotic: ["#4B3BFF", "emit"],
  gamma: ["#E8F4FF", "emit"],
  hazard_black: ["#151515", "solid"],
  crt_bg: ["#0A1A0A", "solid"],
  ghost: ["#00FFFF", "glass"],
  rust: ["#7a4a2a", "solid"],
  concrete: ["#6e6e68", "solid"],
  concrete_dark: ["#55554f", "solid"],
  floor_forge: ["#1c1a24", "solid"],
  white_gold: ["#ffe9a8", "emit"],
  cerulean: ["#3fa7ff", "emit"],
  orange_neon: ["#FF6B00", "emit"],
  lime: ["#AAFF00", "emit"],
  bot_body: ["#8d949c", "metal"],
  bot_dark: ["#454a51", "metal"],
  rubber: ["#222222", "solid"],
  mcp_red: ["#ff2a1a", "emit"],
  // ── Extended palette (interior, devices, characters) ──
  wood_light: ["#a8784a", "solid"],
  wood_red: ["#6b2f22", "solid"],
  oak: ["#8c6239", "solid"],
  walnut: ["#3e2618", "solid"],
  fabric_red: ["#8e2b2b", "solid"],
  fabric_blue: ["#2c3f6b", "solid"],
  fabric_green: ["#2f5a3a", "solid"],
  fabric_gray: ["#5c5f66", "solid"],
  fabric_mustard: ["#b8902c", "solid"],
  leather: ["#5a3522", "solid"],
  leather_black: ["#1e1b1a", "solid"],
  carpet_red: ["#4a1f24", "solid"],
  carpet_blue: ["#1f2a44", "solid"],
  carpet_green: ["#22362a", "solid"],
  tile_white: ["#cfd3d6", "solid"],
  tile_cream: ["#d8cdb0", "solid"],
  tile_black: ["#1c1e21", "solid"],
  tile_teal: ["#2f5e62", "solid"],
  concrete_light: ["#8a8a83", "solid"],
  asphalt: ["#2c2c2e", "solid"],
  steel: ["#8f969e", "metal"],
  steel_dark: ["#50565d", "metal"],
  chrome: ["#c9d0d6", "metal"],
  gold: ["#e0b64a", "metal"],
  aluminium: ["#aeb4ba", "metal"],
  iron_rust: ["#6e3b22", "metal"],
  bronze: ["#8c5a2b", "metal"],
  paint_white: ["#dcdcd4", "solid"],
  paint_cream: ["#e6dcc2", "solid"],
  paint_black: ["#222326", "solid"],
  paint_gray: ["#7a7d82", "solid"],
  paint_navy: ["#1c2a4a", "solid"],
  paint_teal: ["#1f6f78", "solid"],
  paint_mint: ["#8fd1b5", "solid"],
  paint_pink: ["#d06a9a", "solid"],
  paint_lilac: ["#8f7ac2", "solid"],
  paint_lime: ["#9acd32", "solid"],
  paint_sky: ["#6fa8dc", "solid"],
  paint_brick: ["#8b3a2e", "solid"],
  safety_orange: ["#ff7a00", "solid"],
  safety_yellow: ["#ffd400", "solid"],
  safety_green: ["#1fa34a", "solid"],
  safety_red: ["#d6231e", "solid"],
  safety_blue: ["#1f5fbf", "solid"],
  paper_yellow: ["#f3e38a", "solid"],
  paper_pink: ["#f2a7c3", "solid"],
  paper_blue: ["#a9cdf2", "solid"],
  book_red: ["#8a2020", "solid"],
  book_green: ["#1f5e2f", "solid"],
  book_blue: ["#1f3c7a", "solid"],
  book_brown: ["#6b4a2a", "solid"],
  ceramic: ["#eeeae0", "solid"],
  coffee: ["#3b2416", "solid"],
  soil: ["#4a3322", "solid"],
  leaf_dark: ["#2c5e2c", "solid"],
  leaf_light: ["#6aa84f", "solid"],
  flower_red: ["#e0433a", "solid"],
  flower_yellow: ["#f4d03f", "solid"],
  water: ["#3d7fb8", "glass"],
  ice: ["#cfefff", "glass"],
  glass_amber: ["#ffcc70", "glass"],
  glass_red: ["#ff7070", "glass"],
  glass_dark: ["#3a4a5a", "glass"],
  liquid_green: ["#39ff88", "emit"],
  liquid_blue: ["#3fd0ff", "emit"],
  liquid_pink: ["#ff5fd0", "emit"],
  screen_red: ["#ff4040", "emit"],
  screen_blue: ["#4a8cff", "emit"],
  screen_white: ["#f0fff0", "emit"],
  screen_purple: ["#b070ff", "emit"],
  led_blue: ["#2f7bff", "emit"],
  led_white: ["#ffffff", "emit"],
  led_pink: ["#ff3fbf", "emit"],
  lamp_warm: ["#ffd9a0", "emit"],
  lamp_cold: ["#cfe8ff", "emit"],
  fire: ["#ff4a1a", "emit"],
  crystal_violet: ["#9d5cff", "glass"],
  crystal_cyan: ["#5cf2ff", "glass"],
  crystal_rose: ["#ff8ad8", "glass"],
  halo_glow: ["#fff4c8", "emit"],
  hair_black: ["#1a1410", "solid"],
  hair_blond: ["#c9a55a", "solid"],
  hair_brown: ["#4a2c1a", "solid"],
  skin_dark: ["#8d5a3b", "solid"],
  skin_light: ["#f1c9a8", "solid"],
  lips: ["#a8484a", "solid"],
  eye_white: ["#f4f4f4", "solid"],
  eye_green: ["#3f8f5a", "solid"],
  jeans: ["#34507a", "solid"],
  sweater_teal: ["#2d6b6b", "solid"],
  scarf_red: ["#9e2b2b", "solid"],
  badge_blue: ["#1f4fb0", "solid"],
  // ── Wear & material variation (decor weathering pass, see models/decor-weather.ts) ──
  wood_grain: ["#6c4829", "solid"],
  wood_light_grain: ["#96683f", "solid"],
  wood_dark_grain: ["#422a17", "solid"],
  wood_red_grain: ["#5c281d", "solid"],
  oak_grain: ["#7b5532", "solid"],
  walnut_grain: ["#4a2f1f", "solid"],
  fabric_red_shade: ["#7a2424", "solid"],
  fabric_blue_shade: ["#24345a", "solid"],
  fabric_green_shade: ["#274c31", "solid"],
  fabric_gray_shade: ["#4e5157", "solid"],
  fabric_mustard_shade: ["#9e7a24", "solid"],
  leather_worn: ["#74492f", "solid"],
  grime: ["#34302a", "solid"],
  dust: ["#9c9990", "solid"],
  leaf_yellow: ["#a8a040", "solid"],
  lampshade: ["#f0dca8", "glass"],
  // ── Architecture detail (layout.ts: exposed brick, rock, puddles, roots, veins) ──
  brick: ["#7e3a2c", "solid"],
  mortar: ["#a39c8e", "solid"],
  rock: ["#4d4841", "solid"],
  rock_dark: ["#36332f", "solid"],
  puddle: ["#1d3b52", "glass"],
  root: ["#3b2b1d", "solid"],
  vein_cyan: ["#45f0d8", "emit"],
  // ── Refinement shades (lib/world/models/refine.ts: seams, grooves, rivets, wear) ──
  metal_dark_dk: ["#191b1e", "metal"],
  metal_dark_lt: ["#3c3f43", "metal"],
  steel_dark_dk: ["#40454a", "metal"],
  steel_dark_lt: ["#6b7178", "metal"],
  steel_dk: ["#72787e", "metal"],
  chrome_lt: ["#e0e6ec", "metal"],
  copper_lt: ["#cf8d56", "metal"],
  brass_dk: ["#a1821f", "metal"],
  gold_lt: ["#f6cd66", "metal"],
  iron_rust_dk: ["#582f1b", "metal"],
  door_frame_dk: ["#cc9300", "metal"],
  door_frame_lt: ["#ffcf1f", "metal"],
  paint_white_dk: ["#b0b0aa", "solid"],
  paint_black_lt: ["#3f4043", "solid"],
  paint_gray_dk: ["#626468", "solid"],
  paint_gray_lt: ["#94979b", "solid"],
  walnut_dk: ["#321e13", "solid"],
  beige_dk: ["#9d9480", "solid"],
  wall_dk: ["#494d53", "solid"],
  wall_lt: ["#767b82", "solid"],
  wall_dark_dk: ["#313439", "solid"],
  trim_dk: ["#cb9201", "solid"],
  trim_lt: ["#ffcf20", "solid"],
  olive_dk: ["#3b4033", "solid"],
  olive_lt: ["#666b5c", "solid"],
  teal_dk: ["#245656", "solid"],
  teal_lt: ["#4a8585", "solid"],
  wall_beige_dk: ["#6e6756", "solid"],
  wall_beige_lt: ["#a39a86", "solid"],
  tile_white_dk: ["#a6a9ab", "solid"],
  tile_cream_dk: ["#ada48d", "solid"],
  tile_teal_dk: ["#264b4e", "solid"],
  floor_red_dk: ["#2f2222", "solid"],
  floor_beige_dk: ["#3b3830", "solid"],
  blue_paint_dk: ["#224a8d", "solid"],
  purple_paint_dk: ["#49227b", "solid"],
  green_paint_dk: ["#266e3b", "solid"],
  orange_paint_dk: ["#b35215", "solid"],
  paint_teal_dk: ["#195960", "solid"],
  paint_mint_dk: ["#72a791", "solid"],
  // Emissive-class darks: LED bezels and screen scanlines stay in the emit
  // bucket, so a glowing part never gains an extra material (draw call).
  led_bezel: ["#0e0e0e", "emit"],
  scan_dim: ["#0b1c0b", "emit"],
  // Jade Lawrence (2026 rework): pale skin, vivid copper hair, silver lids.
  skin_pale: ["#f4d9c6", "solid"],
  skin_pale_shade: ["#dcb29a", "solid"],
  skin_pale_light: ["#fdebdf", "solid"],
  hair_copper: ["#e2561c", "solid"],
  hair_copper_dk: ["#b23d14", "solid"],
  hair_copper_lt: ["#f5813a", "solid"],
  lid_silver: ["#eef0f5", "solid"],
  // Jade's eyes (reference photo 2026-10): dark brown. Appended so existing indices stay stable.
  eye_brown: ["#4a2c1c", "solid"],
} as const satisfies Record<string, readonly [string, MaterialClass]>;

export type ColorName = keyof typeof ENTRIES;

const NAMES = Object.keys(ENTRIES) as ColorName[];

/** Palette index per color name (1-based; 0 = empty). */
export const C = Object.fromEntries(NAMES.map((n, i) => [n, i + 1])) as Record<ColorName, number>;

export const LAB_PALETTE: Palette = Palette.fromHex(NAMES.map((n) => ENTRIES[n][0]));

const MATERIAL_BY_INDEX: MaterialClass[] = ["solid", ...NAMES.map((n) => ENTRIES[n][1])];

export function labMaterialOf(index: number): MaterialClass {
  return MATERIAL_BY_INDEX[index] ?? "solid";
}

export function colorHex(name: ColorName): string {
  return ENTRIES[name][0];
}
