/**
 * Song levels: bring every song to its genre's target loudness using the
 * measured table (loudness.ts, generated by scripts/audio/loudness.ts).
 * Quiet genres stay a little quieter than driving ones on purpose.
 */
import { SONG_LOUDNESS } from "@/lib/world/audio/songs/loudness";
import type { Genre, SongDef } from "@/lib/world/audio/songs/types";

export const GENRE_TARGET: Readonly<Record<Genre, number>> = {
  ambient: 0.04,
  calm: 0.044,
  classic: 0.046,
  chill: 0.05,
  rhythmic: 0.056,
  electronic: 0.056,
};

/** Gain for a song (×0.5 … ×2.2; 1 when the song has not been measured). */
export function songGain(song: Pick<SongDef, "id" | "genre">): number {
  const l = SONG_LOUDNESS[song.id];
  if (!l || !Number.isFinite(l)) return 1;
  return Math.min(2.2, Math.max(0.5, GENRE_TARGET[song.genre] / l));
}
